from __future__ import annotations

from typing_extensions import NotRequired, TypedDict

from ..core import UNSET, OptionalNullable, SdkBaseModel
from .enums.request_method import RequestMethodOrStr


class ApiV2010AccountCallCallNotificationInstance(SdkBaseModel):
    account_sid: OptionalNullable[str] = UNSET
    """The SID of the `Account <https://www.twilio.com/docs/iam/api/account>`__ that created the Call Notification
    resource."""

    api_version: OptionalNullable[str] = UNSET
    """The API version used to create the Call Notification resource."""

    call_sid: OptionalNullable[str] = UNSET
    """The SID of the `Call <https://www.twilio.com/docs/voice/api/call-resource>`__ the Call Notification resource is
    associated with."""

    date_created: OptionalNullable[str] = UNSET
    """The date and time in GMT that the resource was created specified in `RFC 2822
    <https://www.ietf.org/rfc/rfc2822.txt>`__ format."""

    date_updated: OptionalNullable[str] = UNSET
    """The date and time in GMT that the resource was last updated specified in `RFC 2822
    <https://www.ietf.org/rfc/rfc2822.txt>`__ format."""

    error_code: OptionalNullable[str] = UNSET
    """A unique error code for the error condition that is described in our `Error Dictionary
    <https://www.twilio.com/docs/api/errors>`__."""

    log: OptionalNullable[str] = UNSET
    """An integer log level that corresponds to the type of notification: ``0`` is ERROR, ``1`` is WARNING."""

    message_date: OptionalNullable[str] = UNSET
    """The date the notification was actually generated in `RFC 2822 <https://www.ietf.org/rfc/rfc2822.txt>`__ format.
    Message buffering can cause this value to differ from ``date_created``."""

    message_text: OptionalNullable[str] = UNSET
    """The text of the notification."""

    more_info: OptionalNullable[str] = UNSET
    """The URL for more information about the error condition. This value is a page in our `Error Dictionary
    <https://www.twilio.com/docs/api/errors>`__."""

    request_method: OptionalNullable[RequestMethodOrStr] = UNSET
    """The HTTP method used to generate the notification. If the notification was generated during a phone call, this is
    the HTTP Method used to request the resource on your server. If the notification was generated by your use of our
    REST API, this is the HTTP method used to call the resource on our servers."""

    request_url: OptionalNullable[str] = UNSET
    """The URL of the resource that generated the notification. If the notification was generated during a phone call,
    this is the URL of the resource on your server that caused the notification. If the notification was generated by
    your use of our REST API, this is the URL of the resource you called."""

    request_variables: OptionalNullable[str] = UNSET
    """The HTTP GET or POST variables we sent to your server. However, if the notification was generated by our REST
    API, this contains the HTTP POST or PUT variables you sent to our API."""

    response_body: OptionalNullable[str] = UNSET
    """The HTTP body returned by your server."""

    response_headers: OptionalNullable[str] = UNSET
    """The HTTP headers returned by your server."""

    sid: OptionalNullable[str] = UNSET
    """The unique string that that we created to identify the Call Notification resource."""

    uri: OptionalNullable[str] = UNSET
    """The URI of the resource, relative to ``https://api.twilio.com``."""


class ApiV2010AccountCallCallNotificationInstanceDict(TypedDict):
    account_sid: NotRequired[str | None]
    api_version: NotRequired[str | None]
    call_sid: NotRequired[str | None]
    date_created: NotRequired[str | None]
    date_updated: NotRequired[str | None]
    error_code: NotRequired[str | None]
    log: NotRequired[str | None]
    message_date: NotRequired[str | None]
    message_text: NotRequired[str | None]
    more_info: NotRequired[str | None]
    request_method: NotRequired[RequestMethodOrStr | None]
    request_url: NotRequired[str | None]
    request_variables: NotRequired[str | None]
    response_body: NotRequired[str | None]
    response_headers: NotRequired[str | None]
    sid: NotRequired[str | None]
    uri: NotRequired[str | None]
