from __future__ import annotations

from pydantic import Field
from typing_extensions import NotRequired, TypedDict

from ..core import UNSET, Optional, SdkBaseModel
from .enums.transport import TransportOrStr


class Response(SdkBaseModel):
    """The result of a WebAuthn credential registration via ``navigator.credentials.create()``, as specified in
    `AuthenticatorAttestationResponse
    <https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorAttestationResponse>`__."""

    attestation_object: Optional[str] = Field(default=UNSET, alias="attestationObject")
    """The authenticator data and an attestation statement for a new key pair generated by the authenticator."""

    client_data_json: Optional[str] = Field(default=UNSET, alias="clientDataJSON")
    """This property contains the JSON-compatible serialization of the data passed from the browser to the authenticator
    in order to generate this credential."""

    transports: Optional[list[TransportOrStr]] = UNSET
    """An array of strings providing hints as to the methods the client could use to communicate with the relevant
    authenticator of the public key credential to retrieve."""


class ResponseDict(TypedDict):
    attestation_object: NotRequired[str]
    client_data_json: NotRequired[str]
    transports: NotRequired[list[TransportOrStr]]
