from __future__ import annotations

from typing import Any

from typing_extensions import NotRequired, TypedDict

from ..core import UNSET, OptionalNullable, RFC3339DateTime, SdkBaseModel


class VerifyV2ServiceEntity(SdkBaseModel):
    sid: OptionalNullable[str] = UNSET
    """A 34 character string that uniquely identifies this Entity."""

    identity: OptionalNullable[str] = UNSET
    """The unique external identifier for the Entity of the Service. This identifier should be immutable, not PII,
    length between 8 and 64 characters, and generated by your external system, such as your user's UUID, GUID, or SID.
    It can only contain dash (-) separated alphanumeric characters."""

    account_sid: OptionalNullable[str] = UNSET
    """The unique SID identifier of the Account."""

    service_sid: OptionalNullable[str] = UNSET
    """The unique SID identifier of the Service."""

    date_created: OptionalNullable[RFC3339DateTime] = UNSET
    """The date that this Entity was created, given in `ISO 8601 <https://en.wikipedia.org/wiki/ISO_8601>`__ format."""

    date_updated: OptionalNullable[RFC3339DateTime] = UNSET
    """The date that this Entity was updated, given in `ISO 8601 <https://en.wikipedia.org/wiki/ISO_8601>`__ format."""

    url: OptionalNullable[str] = UNSET
    """The URL of this resource."""

    links: OptionalNullable[Any] = UNSET
    """Contains a dictionary of URL links to nested resources of this Entity."""


class VerifyV2ServiceEntityDict(TypedDict):
    sid: NotRequired[str | None]
    identity: NotRequired[str | None]
    account_sid: NotRequired[str | None]
    service_sid: NotRequired[str | None]
    date_created: NotRequired[RFC3339DateTime | None]
    date_updated: NotRequired[RFC3339DateTime | None]
    url: NotRequired[str | None]
    links: NotRequired[Any | None]
