from __future__ import annotations

from ..auth import AsyncAuthSchemes, AuthSchemes
from ..core import (
    ApiResult,
    AsyncRawClient,
    Date,
    RawClient,
    RawError,
    RequestOptionsOrDict,
    SecuredRawResponse,
    empty_response,
    form_body,
    json_decoder,
    param,
    raw_error_response,
)
from ..errors.update_call_recording_error import UpdateCallRecordingErrorBody, update_call_recording_error_mapper
from ..models.api_v2010_account_call_call_recording import ApiV2010AccountCallCallRecording
from ..models.enums.call_recording_enum_status import CallRecordingEnumStatusOrStr
from ..models.enums.recording_status_callback_method1 import RecordingStatusCallbackMethod1OrStr
from ..models.list_call_recording_response import ListCallRecordingResponse
from ..server.server import Server


class Api20100401CallRecording:
    def __init__(self, client: RawClient, server: Server, auth: AuthSchemes) -> None:
        self._with_raw_response = Api20100401CallRecordingWithRawResponse(client, server, auth)

    def create_call_recording(
        self,
        account_sid: str,
        call_sid: str,
        *,
        recording_status_callback_event: list[str] | None = None,
        recording_status_callback: str | None = None,
        recording_status_callback_method: RecordingStatusCallbackMethod1OrStr | None = None,
        trim: str | None = None,
        recording_channels: str | None = None,
        recording_track: str | None = None,
        recording_configuration_id: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiV2010AccountCallCallRecording:
        """Create a recording for the call

        Args:
            account_sid: The SID of the `Account <https://www.twilio.com/docs/iam/api/account>`__ that will create the
                resource.
            call_sid: The SID of the `Call <https://www.twilio.com/docs/voice/api/call-resource>`__ to associate the
                resource with.
            recording_status_callback_event: The recording status events on which we should call the
                ``recording_status_callback`` URL. Can be: ``in-progress``, ``completed`` and ``absent`` and the default
                is ``completed``. Separate multiple event values with a space.
            recording_status_callback: The URL we should call using the ``recording_status_callback_method`` on each
                recording event specified in ``recording_status_callback_event``. For more information, see
                `RecordingStatusCallback parameters
                <https://www.twilio.com/docs/voice/api/recording#recordingstatuscallback>`__.
            recording_status_callback_method: The HTTP method we should use to call ``recording_status_callback``. Can
                be: ``GET`` or ``POST`` and the default is ``POST``.
            trim: Whether to trim any leading and trailing silence in the recording. Can be: ``trim-silence`` or
                ``do-not-trim`` and the default is ``do-not-trim``. ``trim-silence`` trims the silence from the
                beginning and end of the recording and ``do-not-trim`` does not.
            recording_channels: The number of channels used in the recording. Can be: ``mono`` or ``dual`` and the
                default is ``mono``. ``mono`` records all parties of the call into one channel. ``dual`` records each
                party of a 2-party call into separate channels.
            recording_track: The audio track to record for the call. Can be: ``inbound``, ``outbound`` or ``both``. The
                default is ``both``. ``inbound`` records the audio that is received by Twilio. ``outbound`` records the
                audio that is generated from Twilio. ``both`` records the audio that is received and generated by
                Twilio.
            recording_configuration_id: The identifier of the configuration to be used when creating and processing the
                recording
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.create_call_recording(
            account_sid,
            call_sid,
            recording_status_callback_event=recording_status_callback_event,
            recording_status_callback=recording_status_callback,
            recording_status_callback_method=recording_status_callback_method,
            trim=trim,
            recording_channels=recording_channels,
            recording_track=recording_track,
            recording_configuration_id=recording_configuration_id,
            request_options=request_options,
        ).unwrap()

    def delete_call_recording(
        self, account_sid: str, call_sid: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> None:
        """Delete a recording from your account

        Args:
            account_sid: The SID of the `Account <https://www.twilio.com/docs/iam/api/account>`__ that created the
                Recording resources to delete.
            call_sid: The `Call <https://www.twilio.com/docs/voice/api/call-resource>`__ SID of the resources to delete.
            sid: The Twilio-provided string that uniquely identifies the Recording resource to delete.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            The resource was deleted successfully.

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.delete_call_recording(
            account_sid, call_sid, sid, request_options=request_options
        ).unwrap()

    def fetch_call_recording(
        self, account_sid: str, call_sid: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> ApiV2010AccountCallCallRecording:
        """Fetch an instance of a recording for a call

        Args:
            account_sid: The SID of the `Account <https://www.twilio.com/docs/iam/api/account>`__ that created the
                Recording resource to fetch.
            call_sid: The `Call <https://www.twilio.com/docs/voice/api/call-resource>`__ SID of the resource to fetch.
            sid: The Twilio-provided string that uniquely identifies the Recording resource to fetch.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.fetch_call_recording(
            account_sid, call_sid, sid, request_options=request_options
        ).unwrap()

    def list_call_recording(
        self,
        account_sid: str,
        call_sid: str,
        *,
        date_created: Date | None = None,
        date_created_query: Date | None = None,
        date_created_query_query: Date | None = None,
        page_size: int | None = None,
        page: int | None = None,
        page_token: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ListCallRecordingResponse:
        """Retrieve a list of recordings belonging to the call used to make the request

        Args:
            account_sid: The SID of the `Account <https://www.twilio.com/docs/iam/api/account>`__ that created the
                Recording resources to read.
            call_sid: The `Call <https://www.twilio.com/docs/voice/api/call-resource>`__ SID of the resources to read.
            date_created: The ``date_created`` value, specified as ``YYYY-MM-DD``, of the resources to read. You can
                also specify inequality: ``DateCreated<=YYYY-MM-DD`` will return recordings generated at or before
                midnight on a given date, and ``DateCreated>=YYYY-MM-DD`` returns recordings generated at or after
                midnight on a date.
            date_created_query: The ``date_created`` value, specified as ``YYYY-MM-DD``, of the resources to read. You
                can also specify inequality: ``DateCreated<=YYYY-MM-DD`` will return recordings generated at or before
                midnight on a given date, and ``DateCreated>=YYYY-MM-DD`` returns recordings generated at or after
                midnight on a date.
            date_created_query_query: The ``date_created`` value, specified as ``YYYY-MM-DD``, of the resources to read.
                You can also specify inequality: ``DateCreated<=YYYY-MM-DD`` will return recordings generated at or
                before midnight on a given date, and ``DateCreated>=YYYY-MM-DD`` returns recordings generated at or
                after midnight on a date.
            page_size: How many resources to return in each list page. The default is 50, and the maximum is 1000.
            page: The page index. This value is simply for client state.
            page_token: The page token. This is provided by the API.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.list_call_recording(
            account_sid,
            call_sid,
            date_created=date_created,
            date_created_query=date_created_query,
            date_created_query_query=date_created_query_query,
            page_size=page_size,
            page=page,
            page_token=page_token,
            request_options=request_options,
        ).unwrap()

    def update_call_recording(
        self,
        account_sid: str,
        call_sid: str,
        sid: str,
        status: CallRecordingEnumStatusOrStr,
        *,
        pause_behavior: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiV2010AccountCallCallRecording:
        """Changes the status of the recording to paused, stopped, or in-progress. Note: Pass ``Twilio.CURRENT`` instead
        of recording sid to reference current active recording.

        Args:
            account_sid: The SID of the `Account <https://www.twilio.com/docs/iam/api/account>`__ that created the
                Recording resource to update.
            call_sid: The `Call <https://www.twilio.com/docs/voice/api/call-resource>`__ SID of the resource to update.
            sid: The Twilio-provided string that uniquely identifies the Recording resource to update.
            status: The status of the recording. Can be: ``processing``, ``completed`` and ``absent``. For more detailed
                statuses on in-progress recordings, check out how to `Update a Recording Resource
                <https://www.twilio.com/docs/voice/api/recording#update-a-recording-resource>`__.
            pause_behavior: Whether to record during a pause. Can be: ``skip`` or ``silence`` and the default is
                ``silence``. ``skip`` does not record during the pause period, while ``silence`` will replace the actual
                audio of the call with silence during the pause period. This parameter only applies when setting
                ``status`` is set to ``paused``.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: Request Timeout ``error`` is ``AccountsCallsRecordingsSidJson201041408Error1 | RawError``."""
        return self._with_raw_response.update_call_recording(
            account_sid, call_sid, sid, status, pause_behavior=pause_behavior, request_options=request_options
        ).unwrap()

    @property
    def with_raw_response(self) -> Api20100401CallRecordingWithRawResponse:
        return self._with_raw_response


class AsyncApi20100401CallRecording:
    def __init__(self, client: AsyncRawClient, server: Server, auth: AsyncAuthSchemes) -> None:
        self._with_raw_response = AsyncApi20100401CallRecordingWithRawResponse(client, server, auth)

    async def create_call_recording(
        self,
        account_sid: str,
        call_sid: str,
        *,
        recording_status_callback_event: list[str] | None = None,
        recording_status_callback: str | None = None,
        recording_status_callback_method: RecordingStatusCallbackMethod1OrStr | None = None,
        trim: str | None = None,
        recording_channels: str | None = None,
        recording_track: str | None = None,
        recording_configuration_id: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiV2010AccountCallCallRecording:
        """Create a recording for the call

        Args:
            account_sid: The SID of the `Account <https://www.twilio.com/docs/iam/api/account>`__ that will create the
                resource.
            call_sid: The SID of the `Call <https://www.twilio.com/docs/voice/api/call-resource>`__ to associate the
                resource with.
            recording_status_callback_event: The recording status events on which we should call the
                ``recording_status_callback`` URL. Can be: ``in-progress``, ``completed`` and ``absent`` and the default
                is ``completed``. Separate multiple event values with a space.
            recording_status_callback: The URL we should call using the ``recording_status_callback_method`` on each
                recording event specified in ``recording_status_callback_event``. For more information, see
                `RecordingStatusCallback parameters
                <https://www.twilio.com/docs/voice/api/recording#recordingstatuscallback>`__.
            recording_status_callback_method: The HTTP method we should use to call ``recording_status_callback``. Can
                be: ``GET`` or ``POST`` and the default is ``POST``.
            trim: Whether to trim any leading and trailing silence in the recording. Can be: ``trim-silence`` or
                ``do-not-trim`` and the default is ``do-not-trim``. ``trim-silence`` trims the silence from the
                beginning and end of the recording and ``do-not-trim`` does not.
            recording_channels: The number of channels used in the recording. Can be: ``mono`` or ``dual`` and the
                default is ``mono``. ``mono`` records all parties of the call into one channel. ``dual`` records each
                party of a 2-party call into separate channels.
            recording_track: The audio track to record for the call. Can be: ``inbound``, ``outbound`` or ``both``. The
                default is ``both``. ``inbound`` records the audio that is received by Twilio. ``outbound`` records the
                audio that is generated from Twilio. ``both`` records the audio that is received and generated by
                Twilio.
            recording_configuration_id: The identifier of the configuration to be used when creating and processing the
                recording
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (
            await self._with_raw_response.create_call_recording(
                account_sid,
                call_sid,
                recording_status_callback_event=recording_status_callback_event,
                recording_status_callback=recording_status_callback,
                recording_status_callback_method=recording_status_callback_method,
                trim=trim,
                recording_channels=recording_channels,
                recording_track=recording_track,
                recording_configuration_id=recording_configuration_id,
                request_options=request_options,
            )
        ).unwrap()

    async def delete_call_recording(
        self, account_sid: str, call_sid: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> None:
        """Delete a recording from your account

        Args:
            account_sid: The SID of the `Account <https://www.twilio.com/docs/iam/api/account>`__ that created the
                Recording resources to delete.
            call_sid: The `Call <https://www.twilio.com/docs/voice/api/call-resource>`__ SID of the resources to delete.
            sid: The Twilio-provided string that uniquely identifies the Recording resource to delete.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            The resource was deleted successfully.

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (
            await self._with_raw_response.delete_call_recording(
                account_sid, call_sid, sid, request_options=request_options
            )
        ).unwrap()

    async def fetch_call_recording(
        self, account_sid: str, call_sid: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> ApiV2010AccountCallCallRecording:
        """Fetch an instance of a recording for a call

        Args:
            account_sid: The SID of the `Account <https://www.twilio.com/docs/iam/api/account>`__ that created the
                Recording resource to fetch.
            call_sid: The `Call <https://www.twilio.com/docs/voice/api/call-resource>`__ SID of the resource to fetch.
            sid: The Twilio-provided string that uniquely identifies the Recording resource to fetch.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (
            await self._with_raw_response.fetch_call_recording(
                account_sid, call_sid, sid, request_options=request_options
            )
        ).unwrap()

    async def list_call_recording(
        self,
        account_sid: str,
        call_sid: str,
        *,
        date_created: Date | None = None,
        date_created_query: Date | None = None,
        date_created_query_query: Date | None = None,
        page_size: int | None = None,
        page: int | None = None,
        page_token: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ListCallRecordingResponse:
        """Retrieve a list of recordings belonging to the call used to make the request

        Args:
            account_sid: The SID of the `Account <https://www.twilio.com/docs/iam/api/account>`__ that created the
                Recording resources to read.
            call_sid: The `Call <https://www.twilio.com/docs/voice/api/call-resource>`__ SID of the resources to read.
            date_created: The ``date_created`` value, specified as ``YYYY-MM-DD``, of the resources to read. You can
                also specify inequality: ``DateCreated<=YYYY-MM-DD`` will return recordings generated at or before
                midnight on a given date, and ``DateCreated>=YYYY-MM-DD`` returns recordings generated at or after
                midnight on a date.
            date_created_query: The ``date_created`` value, specified as ``YYYY-MM-DD``, of the resources to read. You
                can also specify inequality: ``DateCreated<=YYYY-MM-DD`` will return recordings generated at or before
                midnight on a given date, and ``DateCreated>=YYYY-MM-DD`` returns recordings generated at or after
                midnight on a date.
            date_created_query_query: The ``date_created`` value, specified as ``YYYY-MM-DD``, of the resources to read.
                You can also specify inequality: ``DateCreated<=YYYY-MM-DD`` will return recordings generated at or
                before midnight on a given date, and ``DateCreated>=YYYY-MM-DD`` returns recordings generated at or
                after midnight on a date.
            page_size: How many resources to return in each list page. The default is 50, and the maximum is 1000.
            page: The page index. This value is simply for client state.
            page_token: The page token. This is provided by the API.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (
            await self._with_raw_response.list_call_recording(
                account_sid,
                call_sid,
                date_created=date_created,
                date_created_query=date_created_query,
                date_created_query_query=date_created_query_query,
                page_size=page_size,
                page=page,
                page_token=page_token,
                request_options=request_options,
            )
        ).unwrap()

    async def update_call_recording(
        self,
        account_sid: str,
        call_sid: str,
        sid: str,
        status: CallRecordingEnumStatusOrStr,
        *,
        pause_behavior: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiV2010AccountCallCallRecording:
        """Changes the status of the recording to paused, stopped, or in-progress. Note: Pass ``Twilio.CURRENT`` instead
        of recording sid to reference current active recording.

        Args:
            account_sid: The SID of the `Account <https://www.twilio.com/docs/iam/api/account>`__ that created the
                Recording resource to update.
            call_sid: The `Call <https://www.twilio.com/docs/voice/api/call-resource>`__ SID of the resource to update.
            sid: The Twilio-provided string that uniquely identifies the Recording resource to update.
            status: The status of the recording. Can be: ``processing``, ``completed`` and ``absent``. For more detailed
                statuses on in-progress recordings, check out how to `Update a Recording Resource
                <https://www.twilio.com/docs/voice/api/recording#update-a-recording-resource>`__.
            pause_behavior: Whether to record during a pause. Can be: ``skip`` or ``silence`` and the default is
                ``silence``. ``skip`` does not record during the pause period, while ``silence`` will replace the actual
                audio of the call with silence during the pause period. This parameter only applies when setting
                ``status`` is set to ``paused``.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: Request Timeout ``error`` is ``AccountsCallsRecordingsSidJson201041408Error1 | RawError``."""
        return (
            await self._with_raw_response.update_call_recording(
                account_sid, call_sid, sid, status, pause_behavior=pause_behavior, request_options=request_options
            )
        ).unwrap()

    @property
    def with_raw_response(self) -> AsyncApi20100401CallRecordingWithRawResponse:
        return self._with_raw_response


class Api20100401CallRecordingWithRawResponse(SecuredRawResponse[RawClient, Server, AuthSchemes]):
    def create_call_recording(
        self,
        account_sid: str,
        call_sid: str,
        *,
        recording_status_callback_event: list[str] | None = None,
        recording_status_callback: str | None = None,
        recording_status_callback_method: RecordingStatusCallbackMethod1OrStr | None = None,
        trim: str | None = None,
        recording_channels: str | None = None,
        recording_track: str | None = None,
        recording_configuration_id: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[ApiV2010AccountCallCallRecording, RawError]:
        """Create a recording for the call

        Args:
            account_sid: The SID of the `Account <https://www.twilio.com/docs/iam/api/account>`__ that will create the
                resource.
            call_sid: The SID of the `Call <https://www.twilio.com/docs/voice/api/call-resource>`__ to associate the
                resource with.
            recording_status_callback_event: The recording status events on which we should call the
                ``recording_status_callback`` URL. Can be: ``in-progress``, ``completed`` and ``absent`` and the default
                is ``completed``. Separate multiple event values with a space.
            recording_status_callback: The URL we should call using the ``recording_status_callback_method`` on each
                recording event specified in ``recording_status_callback_event``. For more information, see
                `RecordingStatusCallback parameters
                <https://www.twilio.com/docs/voice/api/recording#recordingstatuscallback>`__.
            recording_status_callback_method: The HTTP method we should use to call ``recording_status_callback``. Can
                be: ``GET`` or ``POST`` and the default is ``POST``.
            trim: Whether to trim any leading and trailing silence in the recording. Can be: ``trim-silence`` or
                ``do-not-trim`` and the default is ``do-not-trim``. ``trim-silence`` trims the silence from the
                beginning and end of the recording and ``do-not-trim`` does not.
            recording_channels: The number of channels used in the recording. Can be: ``mono`` or ``dual`` and the
                default is ``mono``. ``mono`` records all parties of the call into one channel. ``dual`` records each
                party of a 2-party call into separate channels.
            recording_track: The audio track to record for the call. Can be: ``inbound``, ``outbound`` or ``both``. The
                default is ``both``. ``inbound`` records the audio that is received by Twilio. ``outbound`` records the
                audio that is generated from Twilio. ``both`` records the audio that is received and generated by
                Twilio.
            recording_configuration_id: The identifier of the configuration to be used when creating and processing the
                recording
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="POST",
            url_template=self._server.default("/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Recordings.json"),
            path_params=[param[str]("AccountSid", account_sid), param[str]("CallSid", call_sid)],
            body=form_body(
                [
                    param[list[str] | None]("RecordingStatusCallbackEvent", recording_status_callback_event),
                    param[str | None]("RecordingStatusCallback", recording_status_callback),
                    param[RecordingStatusCallbackMethod1OrStr | None](
                        "RecordingStatusCallbackMethod", recording_status_callback_method
                    ),
                    param[str | None]("Trim", trim),
                    param[str | None]("RecordingChannels", recording_channels),
                    param[str | None]("RecordingTrack", recording_track),
                    param[str | None]("RecordingConfigurationId", recording_configuration_id),
                ],
            ),
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[ApiV2010AccountCallCallRecording],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    def delete_call_recording(
        self, account_sid: str, call_sid: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> ApiResult[None, RawError]:
        """Delete a recording from your account

        Args:
            account_sid: The SID of the `Account <https://www.twilio.com/docs/iam/api/account>`__ that created the
                Recording resources to delete.
            call_sid: The `Call <https://www.twilio.com/docs/voice/api/call-resource>`__ SID of the resources to delete.
            sid: The Twilio-provided string that uniquely identifies the Recording resource to delete.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="DELETE",
            url_template=self._server.default(
                "/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Recordings/{Sid}.json"
            ),
            path_params=[
                param[str]("AccountSid", account_sid), param[str]("CallSid", call_sid), param[str]("Sid", sid)
            ],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=empty_response,
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    def fetch_call_recording(
        self, account_sid: str, call_sid: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> ApiResult[ApiV2010AccountCallCallRecording, RawError]:
        """Fetch an instance of a recording for a call

        Args:
            account_sid: The SID of the `Account <https://www.twilio.com/docs/iam/api/account>`__ that created the
                Recording resource to fetch.
            call_sid: The `Call <https://www.twilio.com/docs/voice/api/call-resource>`__ SID of the resource to fetch.
            sid: The Twilio-provided string that uniquely identifies the Recording resource to fetch.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="GET",
            url_template=self._server.default(
                "/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Recordings/{Sid}.json"
            ),
            path_params=[
                param[str]("AccountSid", account_sid), param[str]("CallSid", call_sid), param[str]("Sid", sid)
            ],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[ApiV2010AccountCallCallRecording],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    def list_call_recording(
        self,
        account_sid: str,
        call_sid: str,
        *,
        date_created: Date | None = None,
        date_created_query: Date | None = None,
        date_created_query_query: Date | None = None,
        page_size: int | None = None,
        page: int | None = None,
        page_token: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[ListCallRecordingResponse, RawError]:
        """Retrieve a list of recordings belonging to the call used to make the request

        Args:
            account_sid: The SID of the `Account <https://www.twilio.com/docs/iam/api/account>`__ that created the
                Recording resources to read.
            call_sid: The `Call <https://www.twilio.com/docs/voice/api/call-resource>`__ SID of the resources to read.
            date_created: The ``date_created`` value, specified as ``YYYY-MM-DD``, of the resources to read. You can
                also specify inequality: ``DateCreated<=YYYY-MM-DD`` will return recordings generated at or before
                midnight on a given date, and ``DateCreated>=YYYY-MM-DD`` returns recordings generated at or after
                midnight on a date.
            date_created_query: The ``date_created`` value, specified as ``YYYY-MM-DD``, of the resources to read. You
                can also specify inequality: ``DateCreated<=YYYY-MM-DD`` will return recordings generated at or before
                midnight on a given date, and ``DateCreated>=YYYY-MM-DD`` returns recordings generated at or after
                midnight on a date.
            date_created_query_query: The ``date_created`` value, specified as ``YYYY-MM-DD``, of the resources to read.
                You can also specify inequality: ``DateCreated<=YYYY-MM-DD`` will return recordings generated at or
                before midnight on a given date, and ``DateCreated>=YYYY-MM-DD`` returns recordings generated at or
                after midnight on a date.
            page_size: How many resources to return in each list page. The default is 50, and the maximum is 1000.
            page: The page index. This value is simply for client state.
            page_token: The page token. This is provided by the API.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="GET",
            url_template=self._server.default("/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Recordings.json"),
            path_params=[param[str]("AccountSid", account_sid), param[str]("CallSid", call_sid)],
            query_params=[
                param[Date | None]("DateCreated", date_created),
                param[Date | None]("DateCreated<", date_created_query),
                param[Date | None]("DateCreated>", date_created_query_query),
                param[int | None]("PageSize", page_size),
                param[int | None]("Page", page),
                param[str | None]("PageToken", page_token),
            ],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[ListCallRecordingResponse],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    def update_call_recording(
        self,
        account_sid: str,
        call_sid: str,
        sid: str,
        status: CallRecordingEnumStatusOrStr,
        *,
        pause_behavior: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[ApiV2010AccountCallCallRecording, UpdateCallRecordingErrorBody]:
        """Changes the status of the recording to paused, stopped, or in-progress. Note: Pass ``Twilio.CURRENT`` instead
        of recording sid to reference current active recording.

        Args:
            account_sid: The SID of the `Account <https://www.twilio.com/docs/iam/api/account>`__ that created the
                Recording resource to update.
            call_sid: The `Call <https://www.twilio.com/docs/voice/api/call-resource>`__ SID of the resource to update.
            sid: The Twilio-provided string that uniquely identifies the Recording resource to update.
            status: The status of the recording. Can be: ``processing``, ``completed`` and ``absent``. For more detailed
                statuses on in-progress recordings, check out how to `Update a Recording Resource
                <https://www.twilio.com/docs/voice/api/recording#update-a-recording-resource>`__.
            pause_behavior: Whether to record during a pause. Can be: ``skip`` or ``silence`` and the default is
                ``silence``. ``skip`` does not record during the pause period, while ``silence`` will replace the actual
                audio of the call with silence during the pause period. This parameter only applies when setting
                ``status`` is set to ``paused``.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="POST",
            url_template=self._server.default(
                "/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Recordings/{Sid}.json"
            ),
            path_params=[
                param[str]("AccountSid", account_sid), param[str]("CallSid", call_sid), param[str]("Sid", sid)
            ],
            body=form_body(
                [
                    param[CallRecordingEnumStatusOrStr]("Status", status),
                    param[str | None]("PauseBehavior", pause_behavior),
                ],
            ),
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[ApiV2010AccountCallCallRecording],
            error_mapper=update_call_recording_error_mapper,
            request_options=request_options,
        )


class AsyncApi20100401CallRecordingWithRawResponse(SecuredRawResponse[AsyncRawClient, Server, AsyncAuthSchemes]):
    async def create_call_recording(
        self,
        account_sid: str,
        call_sid: str,
        *,
        recording_status_callback_event: list[str] | None = None,
        recording_status_callback: str | None = None,
        recording_status_callback_method: RecordingStatusCallbackMethod1OrStr | None = None,
        trim: str | None = None,
        recording_channels: str | None = None,
        recording_track: str | None = None,
        recording_configuration_id: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[ApiV2010AccountCallCallRecording, RawError]:
        """Create a recording for the call

        Args:
            account_sid: The SID of the `Account <https://www.twilio.com/docs/iam/api/account>`__ that will create the
                resource.
            call_sid: The SID of the `Call <https://www.twilio.com/docs/voice/api/call-resource>`__ to associate the
                resource with.
            recording_status_callback_event: The recording status events on which we should call the
                ``recording_status_callback`` URL. Can be: ``in-progress``, ``completed`` and ``absent`` and the default
                is ``completed``. Separate multiple event values with a space.
            recording_status_callback: The URL we should call using the ``recording_status_callback_method`` on each
                recording event specified in ``recording_status_callback_event``. For more information, see
                `RecordingStatusCallback parameters
                <https://www.twilio.com/docs/voice/api/recording#recordingstatuscallback>`__.
            recording_status_callback_method: The HTTP method we should use to call ``recording_status_callback``. Can
                be: ``GET`` or ``POST`` and the default is ``POST``.
            trim: Whether to trim any leading and trailing silence in the recording. Can be: ``trim-silence`` or
                ``do-not-trim`` and the default is ``do-not-trim``. ``trim-silence`` trims the silence from the
                beginning and end of the recording and ``do-not-trim`` does not.
            recording_channels: The number of channels used in the recording. Can be: ``mono`` or ``dual`` and the
                default is ``mono``. ``mono`` records all parties of the call into one channel. ``dual`` records each
                party of a 2-party call into separate channels.
            recording_track: The audio track to record for the call. Can be: ``inbound``, ``outbound`` or ``both``. The
                default is ``both``. ``inbound`` records the audio that is received by Twilio. ``outbound`` records the
                audio that is generated from Twilio. ``both`` records the audio that is received and generated by
                Twilio.
            recording_configuration_id: The identifier of the configuration to be used when creating and processing the
                recording
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="POST",
            url_template=self._server.default("/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Recordings.json"),
            path_params=[param[str]("AccountSid", account_sid), param[str]("CallSid", call_sid)],
            body=form_body(
                [
                    param[list[str] | None]("RecordingStatusCallbackEvent", recording_status_callback_event),
                    param[str | None]("RecordingStatusCallback", recording_status_callback),
                    param[RecordingStatusCallbackMethod1OrStr | None](
                        "RecordingStatusCallbackMethod", recording_status_callback_method
                    ),
                    param[str | None]("Trim", trim),
                    param[str | None]("RecordingChannels", recording_channels),
                    param[str | None]("RecordingTrack", recording_track),
                    param[str | None]("RecordingConfigurationId", recording_configuration_id),
                ],
            ),
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[ApiV2010AccountCallCallRecording],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    async def delete_call_recording(
        self, account_sid: str, call_sid: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> ApiResult[None, RawError]:
        """Delete a recording from your account

        Args:
            account_sid: The SID of the `Account <https://www.twilio.com/docs/iam/api/account>`__ that created the
                Recording resources to delete.
            call_sid: The `Call <https://www.twilio.com/docs/voice/api/call-resource>`__ SID of the resources to delete.
            sid: The Twilio-provided string that uniquely identifies the Recording resource to delete.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="DELETE",
            url_template=self._server.default(
                "/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Recordings/{Sid}.json"
            ),
            path_params=[
                param[str]("AccountSid", account_sid), param[str]("CallSid", call_sid), param[str]("Sid", sid)
            ],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=empty_response,
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    async def fetch_call_recording(
        self, account_sid: str, call_sid: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> ApiResult[ApiV2010AccountCallCallRecording, RawError]:
        """Fetch an instance of a recording for a call

        Args:
            account_sid: The SID of the `Account <https://www.twilio.com/docs/iam/api/account>`__ that created the
                Recording resource to fetch.
            call_sid: The `Call <https://www.twilio.com/docs/voice/api/call-resource>`__ SID of the resource to fetch.
            sid: The Twilio-provided string that uniquely identifies the Recording resource to fetch.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="GET",
            url_template=self._server.default(
                "/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Recordings/{Sid}.json"
            ),
            path_params=[
                param[str]("AccountSid", account_sid), param[str]("CallSid", call_sid), param[str]("Sid", sid)
            ],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[ApiV2010AccountCallCallRecording],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    async def list_call_recording(
        self,
        account_sid: str,
        call_sid: str,
        *,
        date_created: Date | None = None,
        date_created_query: Date | None = None,
        date_created_query_query: Date | None = None,
        page_size: int | None = None,
        page: int | None = None,
        page_token: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[ListCallRecordingResponse, RawError]:
        """Retrieve a list of recordings belonging to the call used to make the request

        Args:
            account_sid: The SID of the `Account <https://www.twilio.com/docs/iam/api/account>`__ that created the
                Recording resources to read.
            call_sid: The `Call <https://www.twilio.com/docs/voice/api/call-resource>`__ SID of the resources to read.
            date_created: The ``date_created`` value, specified as ``YYYY-MM-DD``, of the resources to read. You can
                also specify inequality: ``DateCreated<=YYYY-MM-DD`` will return recordings generated at or before
                midnight on a given date, and ``DateCreated>=YYYY-MM-DD`` returns recordings generated at or after
                midnight on a date.
            date_created_query: The ``date_created`` value, specified as ``YYYY-MM-DD``, of the resources to read. You
                can also specify inequality: ``DateCreated<=YYYY-MM-DD`` will return recordings generated at or before
                midnight on a given date, and ``DateCreated>=YYYY-MM-DD`` returns recordings generated at or after
                midnight on a date.
            date_created_query_query: The ``date_created`` value, specified as ``YYYY-MM-DD``, of the resources to read.
                You can also specify inequality: ``DateCreated<=YYYY-MM-DD`` will return recordings generated at or
                before midnight on a given date, and ``DateCreated>=YYYY-MM-DD`` returns recordings generated at or
                after midnight on a date.
            page_size: How many resources to return in each list page. The default is 50, and the maximum is 1000.
            page: The page index. This value is simply for client state.
            page_token: The page token. This is provided by the API.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="GET",
            url_template=self._server.default("/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Recordings.json"),
            path_params=[param[str]("AccountSid", account_sid), param[str]("CallSid", call_sid)],
            query_params=[
                param[Date | None]("DateCreated", date_created),
                param[Date | None]("DateCreated<", date_created_query),
                param[Date | None]("DateCreated>", date_created_query_query),
                param[int | None]("PageSize", page_size),
                param[int | None]("Page", page),
                param[str | None]("PageToken", page_token),
            ],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[ListCallRecordingResponse],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    async def update_call_recording(
        self,
        account_sid: str,
        call_sid: str,
        sid: str,
        status: CallRecordingEnumStatusOrStr,
        *,
        pause_behavior: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[ApiV2010AccountCallCallRecording, UpdateCallRecordingErrorBody]:
        """Changes the status of the recording to paused, stopped, or in-progress. Note: Pass ``Twilio.CURRENT`` instead
        of recording sid to reference current active recording.

        Args:
            account_sid: The SID of the `Account <https://www.twilio.com/docs/iam/api/account>`__ that created the
                Recording resource to update.
            call_sid: The `Call <https://www.twilio.com/docs/voice/api/call-resource>`__ SID of the resource to update.
            sid: The Twilio-provided string that uniquely identifies the Recording resource to update.
            status: The status of the recording. Can be: ``processing``, ``completed`` and ``absent``. For more detailed
                statuses on in-progress recordings, check out how to `Update a Recording Resource
                <https://www.twilio.com/docs/voice/api/recording#update-a-recording-resource>`__.
            pause_behavior: Whether to record during a pause. Can be: ``skip`` or ``silence`` and the default is
                ``silence``. ``skip`` does not record during the pause period, while ``silence`` will replace the actual
                audio of the call with silence during the pause period. This parameter only applies when setting
                ``status`` is set to ``paused``.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="POST",
            url_template=self._server.default(
                "/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Recordings/{Sid}.json"
            ),
            path_params=[
                param[str]("AccountSid", account_sid), param[str]("CallSid", call_sid), param[str]("Sid", sid)
            ],
            body=form_body(
                [
                    param[CallRecordingEnumStatusOrStr]("Status", status),
                    param[str | None]("PauseBehavior", pause_behavior),
                ],
            ),
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[ApiV2010AccountCallCallRecording],
            error_mapper=update_call_recording_error_mapper,
            request_options=request_options,
        )
