from __future__ import annotations

from ..auth import AsyncAuthSchemes, AuthSchemes
from ..core import (
    ApiResult,
    AsyncRawClient,
    RawClient,
    RawError,
    RequestOptionsOrDict,
    SecuredRawResponse,
    empty_response,
    form_body,
    json_decoder,
    param,
    raw_error_response,
)
from ..models.list_entity_response import ListEntityResponse
from ..models.verify_v2_service_entity import VerifyV2ServiceEntity
from ..server.server import Server


class VerifyV2Entity:
    def __init__(self, client: RawClient, server: Server, auth: AuthSchemes) -> None:
        self._with_raw_response = VerifyV2EntityWithRawResponse(client, server, auth)

    def create_entity(
        self, service_sid: str, identity: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> VerifyV2ServiceEntity:
        """Create a new Entity for the Service

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: The unique external identifier for the Entity of the Service. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            Created

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.create_entity(service_sid, identity, request_options=request_options).unwrap()

    def delete_entity(
        self, service_sid: str, identity: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> None:
        """Delete a specific Entity.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: The unique external identifier for the Entity of the Service. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            The resource was deleted successfully.

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.delete_entity(service_sid, identity, request_options=request_options).unwrap()

    def fetch_entity(
        self, service_sid: str, identity: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> VerifyV2ServiceEntity:
        """Fetch a specific Entity.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: The unique external identifier for the Entity of the Service. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.fetch_entity(service_sid, identity, request_options=request_options).unwrap()

    def list_entity(
        self,
        service_sid: str,
        *,
        page_size: int | None = None,
        page: int | None = None,
        page_token: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ListEntityResponse:
        """Retrieve a list of all Entities for a Service.

        Args:
            service_sid: The unique SID identifier of the Service.
            page_size: How many resources to return in each list page. The default is 50, and the maximum is 1000.
            page: The page index. This value is simply for client state.
            page_token: The page token. This is provided by the API.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.list_entity(
            service_sid, page_size=page_size, page=page, page_token=page_token, request_options=request_options
        ).unwrap()

    @property
    def with_raw_response(self) -> VerifyV2EntityWithRawResponse:
        return self._with_raw_response


class AsyncVerifyV2Entity:
    def __init__(self, client: AsyncRawClient, server: Server, auth: AsyncAuthSchemes) -> None:
        self._with_raw_response = AsyncVerifyV2EntityWithRawResponse(client, server, auth)

    async def create_entity(
        self, service_sid: str, identity: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> VerifyV2ServiceEntity:
        """Create a new Entity for the Service

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: The unique external identifier for the Entity of the Service. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            Created

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (
            await self._with_raw_response.create_entity(service_sid, identity, request_options=request_options)
        ).unwrap()

    async def delete_entity(
        self, service_sid: str, identity: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> None:
        """Delete a specific Entity.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: The unique external identifier for the Entity of the Service. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            The resource was deleted successfully.

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (
            await self._with_raw_response.delete_entity(service_sid, identity, request_options=request_options)
        ).unwrap()

    async def fetch_entity(
        self, service_sid: str, identity: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> VerifyV2ServiceEntity:
        """Fetch a specific Entity.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: The unique external identifier for the Entity of the Service. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (
            await self._with_raw_response.fetch_entity(service_sid, identity, request_options=request_options)
        ).unwrap()

    async def list_entity(
        self,
        service_sid: str,
        *,
        page_size: int | None = None,
        page: int | None = None,
        page_token: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ListEntityResponse:
        """Retrieve a list of all Entities for a Service.

        Args:
            service_sid: The unique SID identifier of the Service.
            page_size: How many resources to return in each list page. The default is 50, and the maximum is 1000.
            page: The page index. This value is simply for client state.
            page_token: The page token. This is provided by the API.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (
            await self._with_raw_response.list_entity(
                service_sid, page_size=page_size, page=page, page_token=page_token, request_options=request_options
            )
        ).unwrap()

    @property
    def with_raw_response(self) -> AsyncVerifyV2EntityWithRawResponse:
        return self._with_raw_response


class VerifyV2EntityWithRawResponse(SecuredRawResponse[RawClient, Server, AuthSchemes]):
    def create_entity(
        self, service_sid: str, identity: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> ApiResult[VerifyV2ServiceEntity, RawError]:
        """Create a new Entity for the Service

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: The unique external identifier for the Entity of the Service. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="POST",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities"),
            path_params=[param[str]("ServiceSid", service_sid)],
            body=form_body([param[str]("Identity", identity)]),
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[VerifyV2ServiceEntity],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    def delete_entity(
        self, service_sid: str, identity: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> ApiResult[None, RawError]:
        """Delete a specific Entity.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: The unique external identifier for the Entity of the Service. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="DELETE",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities/{Identity}"),
            path_params=[param[str]("ServiceSid", service_sid), param[str]("Identity", identity)],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=empty_response,
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    def fetch_entity(
        self, service_sid: str, identity: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> ApiResult[VerifyV2ServiceEntity, RawError]:
        """Fetch a specific Entity.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: The unique external identifier for the Entity of the Service. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="GET",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities/{Identity}"),
            path_params=[param[str]("ServiceSid", service_sid), param[str]("Identity", identity)],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[VerifyV2ServiceEntity],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    def list_entity(
        self,
        service_sid: str,
        *,
        page_size: int | None = None,
        page: int | None = None,
        page_token: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[ListEntityResponse, RawError]:
        """Retrieve a list of all Entities for a Service.

        Args:
            service_sid: The unique SID identifier of the Service.
            page_size: How many resources to return in each list page. The default is 50, and the maximum is 1000.
            page: The page index. This value is simply for client state.
            page_token: The page token. This is provided by the API.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="GET",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities"),
            path_params=[param[str]("ServiceSid", service_sid)],
            query_params=[
                param[int | None]("PageSize", page_size),
                param[int | None]("Page", page),
                param[str | None]("PageToken", page_token),
            ],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[ListEntityResponse],
            error_mapper=raw_error_response,
            request_options=request_options,
        )


class AsyncVerifyV2EntityWithRawResponse(SecuredRawResponse[AsyncRawClient, Server, AsyncAuthSchemes]):
    async def create_entity(
        self, service_sid: str, identity: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> ApiResult[VerifyV2ServiceEntity, RawError]:
        """Create a new Entity for the Service

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: The unique external identifier for the Entity of the Service. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="POST",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities"),
            path_params=[param[str]("ServiceSid", service_sid)],
            body=form_body([param[str]("Identity", identity)]),
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[VerifyV2ServiceEntity],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    async def delete_entity(
        self, service_sid: str, identity: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> ApiResult[None, RawError]:
        """Delete a specific Entity.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: The unique external identifier for the Entity of the Service. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="DELETE",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities/{Identity}"),
            path_params=[param[str]("ServiceSid", service_sid), param[str]("Identity", identity)],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=empty_response,
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    async def fetch_entity(
        self, service_sid: str, identity: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> ApiResult[VerifyV2ServiceEntity, RawError]:
        """Fetch a specific Entity.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: The unique external identifier for the Entity of the Service. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="GET",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities/{Identity}"),
            path_params=[param[str]("ServiceSid", service_sid), param[str]("Identity", identity)],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[VerifyV2ServiceEntity],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    async def list_entity(
        self,
        service_sid: str,
        *,
        page_size: int | None = None,
        page: int | None = None,
        page_token: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[ListEntityResponse, RawError]:
        """Retrieve a list of all Entities for a Service.

        Args:
            service_sid: The unique SID identifier of the Service.
            page_size: How many resources to return in each list page. The default is 50, and the maximum is 1000.
            page: The page index. This value is simply for client state.
            page_token: The page token. This is provided by the API.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="GET",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities"),
            path_params=[param[str]("ServiceSid", service_sid)],
            query_params=[
                param[int | None]("PageSize", page_size),
                param[int | None]("Page", page),
                param[str | None]("PageToken", page_token),
            ],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[ListEntityResponse],
            error_mapper=raw_error_response,
            request_options=request_options,
        )
