from __future__ import annotations

from ..auth import AsyncAuthSchemes, AuthSchemes
from ..core import (
    ApiResult,
    AsyncRawClient,
    RawClient,
    RawError,
    RequestOptionsOrDict,
    SecuredRawResponse,
    json_decoder,
    param,
    raw_error_response,
)
from ..models.insights_v1_conference_conference_participant import InsightsV1ConferenceConferenceParticipant
from ..models.list_conference_participant_response import ListConferenceParticipantResponse
from ..server.server import Server


class InsightsV1ConferenceParticipant:
    def __init__(self, client: RawClient, server: Server, auth: AuthSchemes) -> None:
        self._with_raw_response = InsightsV1ConferenceParticipantWithRawResponse(client, server, auth)

    def fetch_conference_participant(
        self,
        conference_sid: str,
        participant_sid: str,
        *,
        events: str | None = None,
        metrics: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> InsightsV1ConferenceConferenceParticipant:
        """Get a specific Conference Participant Summary for a Conference.

        Args:
            conference_sid: The unique SID identifier of the Conference.
            participant_sid: The unique SID identifier of the Participant.
            events: Conference events generated by application or participant activity; e.g. ``hold``, ``mute``, etc.
            metrics: Object. Contains participant call quality metrics.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.fetch_conference_participant(
            conference_sid, participant_sid, events=events, metrics=metrics, request_options=request_options
        ).unwrap()

    def list_conference_participant(
        self,
        conference_sid: str,
        *,
        participant_sid: str | None = None,
        label: str | None = None,
        events: str | None = None,
        page_size: int | None = None,
        page: int | None = None,
        page_token: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ListConferenceParticipantResponse:
        """Get a list of Conference Participants Summaries for a Conference.

        Args:
            conference_sid: The unique SID identifier of the Conference.
            participant_sid: The unique SID identifier of the Participant.
            label: User-specified label for a participant.
            events: Conference events generated by application or participant activity; e.g. ``hold``, ``mute``, etc.
            page_size: How many resources to return in each list page. The default is 50, and the maximum is 1000.
            page: The page index. This value is simply for client state.
            page_token: The page token. This is provided by the API.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.list_conference_participant(
            conference_sid,
            participant_sid=participant_sid,
            label=label,
            events=events,
            page_size=page_size,
            page=page,
            page_token=page_token,
            request_options=request_options,
        ).unwrap()

    @property
    def with_raw_response(self) -> InsightsV1ConferenceParticipantWithRawResponse:
        return self._with_raw_response


class AsyncInsightsV1ConferenceParticipant:
    def __init__(self, client: AsyncRawClient, server: Server, auth: AsyncAuthSchemes) -> None:
        self._with_raw_response = AsyncInsightsV1ConferenceParticipantWithRawResponse(client, server, auth)

    async def fetch_conference_participant(
        self,
        conference_sid: str,
        participant_sid: str,
        *,
        events: str | None = None,
        metrics: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> InsightsV1ConferenceConferenceParticipant:
        """Get a specific Conference Participant Summary for a Conference.

        Args:
            conference_sid: The unique SID identifier of the Conference.
            participant_sid: The unique SID identifier of the Participant.
            events: Conference events generated by application or participant activity; e.g. ``hold``, ``mute``, etc.
            metrics: Object. Contains participant call quality metrics.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (
            await self._with_raw_response.fetch_conference_participant(
                conference_sid, participant_sid, events=events, metrics=metrics, request_options=request_options
            )
        ).unwrap()

    async def list_conference_participant(
        self,
        conference_sid: str,
        *,
        participant_sid: str | None = None,
        label: str | None = None,
        events: str | None = None,
        page_size: int | None = None,
        page: int | None = None,
        page_token: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ListConferenceParticipantResponse:
        """Get a list of Conference Participants Summaries for a Conference.

        Args:
            conference_sid: The unique SID identifier of the Conference.
            participant_sid: The unique SID identifier of the Participant.
            label: User-specified label for a participant.
            events: Conference events generated by application or participant activity; e.g. ``hold``, ``mute``, etc.
            page_size: How many resources to return in each list page. The default is 50, and the maximum is 1000.
            page: The page index. This value is simply for client state.
            page_token: The page token. This is provided by the API.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (
            await self._with_raw_response.list_conference_participant(
                conference_sid,
                participant_sid=participant_sid,
                label=label,
                events=events,
                page_size=page_size,
                page=page,
                page_token=page_token,
                request_options=request_options,
            )
        ).unwrap()

    @property
    def with_raw_response(self) -> AsyncInsightsV1ConferenceParticipantWithRawResponse:
        return self._with_raw_response


class InsightsV1ConferenceParticipantWithRawResponse(SecuredRawResponse[RawClient, Server, AuthSchemes]):
    def fetch_conference_participant(
        self,
        conference_sid: str,
        participant_sid: str,
        *,
        events: str | None = None,
        metrics: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[InsightsV1ConferenceConferenceParticipant, RawError]:
        """Get a specific Conference Participant Summary for a Conference.

        Args:
            conference_sid: The unique SID identifier of the Conference.
            participant_sid: The unique SID identifier of the Participant.
            events: Conference events generated by application or participant activity; e.g. ``hold``, ``mute``, etc.
            metrics: Object. Contains participant call quality metrics.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="GET",
            url_template=self._server.default14("/v1/Conferences/{ConferenceSid}/Participants/{ParticipantSid}"),
            path_params=[param[str]("ConferenceSid", conference_sid), param[str]("ParticipantSid", participant_sid)],
            query_params=[param[str | None]("Events", events), param[str | None]("Metrics", metrics)],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[InsightsV1ConferenceConferenceParticipant],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    def list_conference_participant(
        self,
        conference_sid: str,
        *,
        participant_sid: str | None = None,
        label: str | None = None,
        events: str | None = None,
        page_size: int | None = None,
        page: int | None = None,
        page_token: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[ListConferenceParticipantResponse, RawError]:
        """Get a list of Conference Participants Summaries for a Conference.

        Args:
            conference_sid: The unique SID identifier of the Conference.
            participant_sid: The unique SID identifier of the Participant.
            label: User-specified label for a participant.
            events: Conference events generated by application or participant activity; e.g. ``hold``, ``mute``, etc.
            page_size: How many resources to return in each list page. The default is 50, and the maximum is 1000.
            page: The page index. This value is simply for client state.
            page_token: The page token. This is provided by the API.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="GET",
            url_template=self._server.default14("/v1/Conferences/{ConferenceSid}/Participants"),
            path_params=[param[str]("ConferenceSid", conference_sid)],
            query_params=[
                param[str | None]("ParticipantSid", participant_sid),
                param[str | None]("Label", label),
                param[str | None]("Events", events),
                param[int | None]("PageSize", page_size),
                param[int | None]("Page", page),
                param[str | None]("PageToken", page_token),
            ],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[ListConferenceParticipantResponse],
            error_mapper=raw_error_response,
            request_options=request_options,
        )


class AsyncInsightsV1ConferenceParticipantWithRawResponse(SecuredRawResponse[AsyncRawClient, Server, AsyncAuthSchemes]):
    async def fetch_conference_participant(
        self,
        conference_sid: str,
        participant_sid: str,
        *,
        events: str | None = None,
        metrics: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[InsightsV1ConferenceConferenceParticipant, RawError]:
        """Get a specific Conference Participant Summary for a Conference.

        Args:
            conference_sid: The unique SID identifier of the Conference.
            participant_sid: The unique SID identifier of the Participant.
            events: Conference events generated by application or participant activity; e.g. ``hold``, ``mute``, etc.
            metrics: Object. Contains participant call quality metrics.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="GET",
            url_template=self._server.default14("/v1/Conferences/{ConferenceSid}/Participants/{ParticipantSid}"),
            path_params=[param[str]("ConferenceSid", conference_sid), param[str]("ParticipantSid", participant_sid)],
            query_params=[param[str | None]("Events", events), param[str | None]("Metrics", metrics)],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[InsightsV1ConferenceConferenceParticipant],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    async def list_conference_participant(
        self,
        conference_sid: str,
        *,
        participant_sid: str | None = None,
        label: str | None = None,
        events: str | None = None,
        page_size: int | None = None,
        page: int | None = None,
        page_token: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[ListConferenceParticipantResponse, RawError]:
        """Get a list of Conference Participants Summaries for a Conference.

        Args:
            conference_sid: The unique SID identifier of the Conference.
            participant_sid: The unique SID identifier of the Participant.
            label: User-specified label for a participant.
            events: Conference events generated by application or participant activity; e.g. ``hold``, ``mute``, etc.
            page_size: How many resources to return in each list page. The default is 50, and the maximum is 1000.
            page: The page index. This value is simply for client state.
            page_token: The page token. This is provided by the API.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="GET",
            url_template=self._server.default14("/v1/Conferences/{ConferenceSid}/Participants"),
            path_params=[param[str]("ConferenceSid", conference_sid)],
            query_params=[
                param[str | None]("ParticipantSid", participant_sid),
                param[str | None]("Label", label),
                param[str | None]("Events", events),
                param[int | None]("PageSize", page_size),
                param[int | None]("Page", page),
                param[str | None]("PageToken", page_token),
            ],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[ListConferenceParticipantResponse],
            error_mapper=raw_error_response,
            request_options=request_options,
        )
