from __future__ import annotations

from ..auth import AsyncAuthSchemes, AuthSchemes
from ..core import (
    ApiResult,
    AsyncRawClient,
    RawClient,
    RawError,
    RequestOptionsOrDict,
    SecuredRawResponse,
    form_body,
    json_decoder,
    param,
    raw_error_response,
)
from ..models.enums.access_token_enum_factor_types import AccessTokenEnumFactorTypesOrStr
from ..models.verify_v2_service_access_token import VerifyV2ServiceAccessToken
from ..server.server import Server


class VerifyV2AccessToken:
    def __init__(self, client: RawClient, server: Server, auth: AuthSchemes) -> None:
        self._with_raw_response = VerifyV2AccessTokenWithRawResponse(client, server, auth)

    def create_access_token(
        self,
        service_sid: str,
        identity: str,
        factor_type: AccessTokenEnumFactorTypesOrStr,
        *,
        factor_friendly_name: str | None = None,
        ttl: int | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> VerifyV2ServiceAccessToken:
        """Create a new enrollment Access Token for the Entity

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: The unique external identifier for the Entity of the Service. This identifier should be immutable,
                not PII, and generated by your external system, such as your user's UUID, GUID, or SID.
            factor_type: The Type of the Factor. Currently only ``push`` is supported.
            factor_friendly_name: The friendly name of the factor that is going to be created with this access token
            ttl: How long, in seconds, the access token is valid. Can be an integer between 60 and 300. Default is 60.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            Created

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.create_access_token(
            service_sid,
            identity,
            factor_type,
            factor_friendly_name=factor_friendly_name,
            ttl=ttl,
            request_options=request_options,
        ).unwrap()

    def fetch_access_token(
        self, service_sid: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> VerifyV2ServiceAccessToken:
        """Fetch an Access Token for the Entity

        Args:
            service_sid: The unique SID identifier of the Service.
            sid: A 34 character string that uniquely identifies this Access Token.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.fetch_access_token(service_sid, sid, request_options=request_options).unwrap()

    @property
    def with_raw_response(self) -> VerifyV2AccessTokenWithRawResponse:
        return self._with_raw_response


class AsyncVerifyV2AccessToken:
    def __init__(self, client: AsyncRawClient, server: Server, auth: AsyncAuthSchemes) -> None:
        self._with_raw_response = AsyncVerifyV2AccessTokenWithRawResponse(client, server, auth)

    async def create_access_token(
        self,
        service_sid: str,
        identity: str,
        factor_type: AccessTokenEnumFactorTypesOrStr,
        *,
        factor_friendly_name: str | None = None,
        ttl: int | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> VerifyV2ServiceAccessToken:
        """Create a new enrollment Access Token for the Entity

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: The unique external identifier for the Entity of the Service. This identifier should be immutable,
                not PII, and generated by your external system, such as your user's UUID, GUID, or SID.
            factor_type: The Type of the Factor. Currently only ``push`` is supported.
            factor_friendly_name: The friendly name of the factor that is going to be created with this access token
            ttl: How long, in seconds, the access token is valid. Can be an integer between 60 and 300. Default is 60.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            Created

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (
            await self._with_raw_response.create_access_token(
                service_sid,
                identity,
                factor_type,
                factor_friendly_name=factor_friendly_name,
                ttl=ttl,
                request_options=request_options,
            )
        ).unwrap()

    async def fetch_access_token(
        self, service_sid: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> VerifyV2ServiceAccessToken:
        """Fetch an Access Token for the Entity

        Args:
            service_sid: The unique SID identifier of the Service.
            sid: A 34 character string that uniquely identifies this Access Token.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (
            await self._with_raw_response.fetch_access_token(service_sid, sid, request_options=request_options)
        ).unwrap()

    @property
    def with_raw_response(self) -> AsyncVerifyV2AccessTokenWithRawResponse:
        return self._with_raw_response


class VerifyV2AccessTokenWithRawResponse(SecuredRawResponse[RawClient, Server, AuthSchemes]):
    def create_access_token(
        self,
        service_sid: str,
        identity: str,
        factor_type: AccessTokenEnumFactorTypesOrStr,
        *,
        factor_friendly_name: str | None = None,
        ttl: int | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[VerifyV2ServiceAccessToken, RawError]:
        """Create a new enrollment Access Token for the Entity

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: The unique external identifier for the Entity of the Service. This identifier should be immutable,
                not PII, and generated by your external system, such as your user's UUID, GUID, or SID.
            factor_type: The Type of the Factor. Currently only ``push`` is supported.
            factor_friendly_name: The friendly name of the factor that is going to be created with this access token
            ttl: How long, in seconds, the access token is valid. Can be an integer between 60 and 300. Default is 60.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="POST",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/AccessTokens"),
            path_params=[param[str]("ServiceSid", service_sid)],
            body=form_body(
                [
                    param[str]("Identity", identity),
                    param[AccessTokenEnumFactorTypesOrStr]("FactorType", factor_type),
                    param[str | None]("FactorFriendlyName", factor_friendly_name),
                    param[int | None]("Ttl", ttl),
                ],
            ),
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[VerifyV2ServiceAccessToken],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    def fetch_access_token(
        self, service_sid: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> ApiResult[VerifyV2ServiceAccessToken, RawError]:
        """Fetch an Access Token for the Entity

        Args:
            service_sid: The unique SID identifier of the Service.
            sid: A 34 character string that uniquely identifies this Access Token.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="GET",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/AccessTokens/{Sid}"),
            path_params=[param[str]("ServiceSid", service_sid), param[str]("Sid", sid)],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[VerifyV2ServiceAccessToken],
            error_mapper=raw_error_response,
            request_options=request_options,
        )


class AsyncVerifyV2AccessTokenWithRawResponse(SecuredRawResponse[AsyncRawClient, Server, AsyncAuthSchemes]):
    async def create_access_token(
        self,
        service_sid: str,
        identity: str,
        factor_type: AccessTokenEnumFactorTypesOrStr,
        *,
        factor_friendly_name: str | None = None,
        ttl: int | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[VerifyV2ServiceAccessToken, RawError]:
        """Create a new enrollment Access Token for the Entity

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: The unique external identifier for the Entity of the Service. This identifier should be immutable,
                not PII, and generated by your external system, such as your user's UUID, GUID, or SID.
            factor_type: The Type of the Factor. Currently only ``push`` is supported.
            factor_friendly_name: The friendly name of the factor that is going to be created with this access token
            ttl: How long, in seconds, the access token is valid. Can be an integer between 60 and 300. Default is 60.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="POST",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/AccessTokens"),
            path_params=[param[str]("ServiceSid", service_sid)],
            body=form_body(
                [
                    param[str]("Identity", identity),
                    param[AccessTokenEnumFactorTypesOrStr]("FactorType", factor_type),
                    param[str | None]("FactorFriendlyName", factor_friendly_name),
                    param[int | None]("Ttl", ttl),
                ],
            ),
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[VerifyV2ServiceAccessToken],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    async def fetch_access_token(
        self, service_sid: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> ApiResult[VerifyV2ServiceAccessToken, RawError]:
        """Fetch an Access Token for the Entity

        Args:
            service_sid: The unique SID identifier of the Service.
            sid: A 34 character string that uniquely identifies this Access Token.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="GET",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/AccessTokens/{Sid}"),
            path_params=[param[str]("ServiceSid", service_sid), param[str]("Sid", sid)],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[VerifyV2ServiceAccessToken],
            error_mapper=raw_error_response,
            request_options=request_options,
        )
