from __future__ import annotations

from uuid import UUID, uuid4

from ..auth import AsyncAuthSchemes, AuthSchemes
from ..core import (
    ApiResult,
    AsyncRawClient,
    RawClient,
    RawError,
    RequestOptionsOrDict,
    SecuredRawResponse,
    form_body,
    json_decoder,
    param,
    raw_error_response,
)
from ..models.verify_v2_service_entity_challenge_notification import VerifyV2ServiceEntityChallengeNotification
from ..server.server import Server


class VerifyV2Notification:
    def __init__(self, client: RawClient, server: Server, auth: AuthSchemes) -> None:
        self._with_raw_response = VerifyV2NotificationWithRawResponse(client, server, auth)

    def create_notification(
        self,
        service_sid: str,
        identity: str,
        challenge_sid: str,
        *,
        ttl: int | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> VerifyV2ServiceEntityChallengeNotification:
        """Create a new Notification for the corresponding Challenge

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Challenge. This identifier should be
                immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as
                your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            challenge_sid: The unique SID identifier of the Challenge.
            ttl: How long, in seconds, the notification is valid. Can be an integer between 0 and 300. Default is 300.
                Delivery is attempted until the TTL elapses, even if the device is offline. 0 means that the
                notification delivery is attempted immediately, only once, and is not stored for future delivery.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            Created

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.create_notification(
            service_sid, identity, challenge_sid, ttl=ttl, request_options=request_options
        ).unwrap()

    @property
    def with_raw_response(self) -> VerifyV2NotificationWithRawResponse:
        return self._with_raw_response


class AsyncVerifyV2Notification:
    def __init__(self, client: AsyncRawClient, server: Server, auth: AsyncAuthSchemes) -> None:
        self._with_raw_response = AsyncVerifyV2NotificationWithRawResponse(client, server, auth)

    async def create_notification(
        self,
        service_sid: str,
        identity: str,
        challenge_sid: str,
        *,
        ttl: int | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> VerifyV2ServiceEntityChallengeNotification:
        """Create a new Notification for the corresponding Challenge

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Challenge. This identifier should be
                immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as
                your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            challenge_sid: The unique SID identifier of the Challenge.
            ttl: How long, in seconds, the notification is valid. Can be an integer between 0 and 300. Default is 300.
                Delivery is attempted until the TTL elapses, even if the device is offline. 0 means that the
                notification delivery is attempted immediately, only once, and is not stored for future delivery.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            Created

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (
            await self._with_raw_response.create_notification(
                service_sid, identity, challenge_sid, ttl=ttl, request_options=request_options
            )
        ).unwrap()

    @property
    def with_raw_response(self) -> AsyncVerifyV2NotificationWithRawResponse:
        return self._with_raw_response


class VerifyV2NotificationWithRawResponse(SecuredRawResponse[RawClient, Server, AuthSchemes]):
    def create_notification(
        self,
        service_sid: str,
        identity: str,
        challenge_sid: str,
        *,
        ttl: int | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[VerifyV2ServiceEntityChallengeNotification, RawError]:
        """Create a new Notification for the corresponding Challenge

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Challenge. This identifier should be
                immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as
                your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            challenge_sid: The unique SID identifier of the Challenge.
            ttl: How long, in seconds, the notification is valid. Can be an integer between 0 and 300. Default is 300.
                Delivery is attempted until the TTL elapses, even if the device is offline. 0 means that the
                notification delivery is attempted immediately, only once, and is not stored for future delivery.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="POST",
            url_template=self._server.default3(
                "/v2/Services/{ServiceSid}/Entities/{Identity}/Challenges/{ChallengeSid}/Notifications"
            ),
            path_params=[
                param[str]("ServiceSid", service_sid),
                param[str]("Identity", identity),
                param[str]("ChallengeSid", challenge_sid),
            ],
            headers=[param[UUID]("Idempotency-Key", uuid4())],
            body=form_body([param[int | None]("Ttl", ttl)]),
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[VerifyV2ServiceEntityChallengeNotification],
            error_mapper=raw_error_response,
            request_options=request_options,
        )


class AsyncVerifyV2NotificationWithRawResponse(SecuredRawResponse[AsyncRawClient, Server, AsyncAuthSchemes]):
    async def create_notification(
        self,
        service_sid: str,
        identity: str,
        challenge_sid: str,
        *,
        ttl: int | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[VerifyV2ServiceEntityChallengeNotification, RawError]:
        """Create a new Notification for the corresponding Challenge

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Challenge. This identifier should be
                immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as
                your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            challenge_sid: The unique SID identifier of the Challenge.
            ttl: How long, in seconds, the notification is valid. Can be an integer between 0 and 300. Default is 300.
                Delivery is attempted until the TTL elapses, even if the device is offline. 0 means that the
                notification delivery is attempted immediately, only once, and is not stored for future delivery.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="POST",
            url_template=self._server.default3(
                "/v2/Services/{ServiceSid}/Entities/{Identity}/Challenges/{ChallengeSid}/Notifications"
            ),
            path_params=[
                param[str]("ServiceSid", service_sid),
                param[str]("Identity", identity),
                param[str]("ChallengeSid", challenge_sid),
            ],
            headers=[param[UUID]("Idempotency-Key", uuid4())],
            body=form_body([param[int | None]("Ttl", ttl)]),
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[VerifyV2ServiceEntityChallengeNotification],
            error_mapper=raw_error_response,
            request_options=request_options,
        )
