from __future__ import annotations

from uuid import UUID, uuid4

from ..auth import AsyncAuthSchemes, AuthSchemes
from ..core import (
    ApiResult,
    AsyncRawClient,
    RawClient,
    RawError,
    RequestOptionsOrDict,
    SecuredRawResponse,
    empty_response,
    form_body,
    json_decoder,
    param,
    raw_error_response,
)
from ..models.enums.factor_enum_totp_algorithms import FactorEnumTotpAlgorithmsOrStr
from ..models.list_factor_response import ListFactorResponse
from ..models.verify_v2_service_entity_factor import VerifyV2ServiceEntityFactor
from ..server.server import Server


class VerifyV2Factor:
    def __init__(self, client: RawClient, server: Server, auth: AuthSchemes) -> None:
        self._with_raw_response = VerifyV2FactorWithRawResponse(client, server, auth)

    def delete_factor(
        self, service_sid: str, identity: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> None:
        """Delete a specific Factor.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Factor. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            sid: A 34 character string that uniquely identifies this Factor.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            The resource was deleted successfully.

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.delete_factor(
            service_sid, identity, sid, request_options=request_options
        ).unwrap()

    def fetch_factor(
        self, service_sid: str, identity: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> VerifyV2ServiceEntityFactor:
        """Fetch a specific Factor.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Factor. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            sid: A 34 character string that uniquely identifies this Factor.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.fetch_factor(
            service_sid, identity, sid, request_options=request_options
        ).unwrap()

    def list_factor(
        self,
        service_sid: str,
        identity: str,
        *,
        page_size: int | None = None,
        page: int | None = None,
        page_token: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ListFactorResponse:
        """Retrieve a list of all Factors for an Entity.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Factors. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            page_size: How many resources to return in each list page. The default is 50, and the maximum is 1000.
            page: The page index. This value is simply for client state.
            page_token: The page token. This is provided by the API.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.list_factor(
            service_sid,
            identity,
            page_size=page_size,
            page=page,
            page_token=page_token,
            request_options=request_options,
        ).unwrap()

    def update_factor(
        self,
        service_sid: str,
        identity: str,
        sid: str,
        *,
        auth_payload: str | None = None,
        friendly_name: str | None = None,
        config_notification_token: str | None = None,
        config_sdk_version: str | None = None,
        config_time_step: int | None = None,
        config_skew: int | None = None,
        config_code_length: int | None = None,
        config_alg: FactorEnumTotpAlgorithmsOrStr | None = None,
        config_notification_platform: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> VerifyV2ServiceEntityFactor:
        """Update a specific Factor. This endpoint can be used to Verify a Factor if passed an ``AuthPayload`` param.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Factor. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            sid: A 34 character string that uniquely identifies this Factor.
            auth_payload: The optional payload needed to verify the Factor for the first time. E.g. for a TOTP, the
                numeric code.
            friendly_name: The new friendly name of this Factor. It can be up to 64 characters.
            config_notification_token: For APN, the device token. For FCM, the registration token. It is used to send
                the push notifications. Required when ``factor_type`` is ``push``. If specified, this value must be
                between 32 and 255 characters long.
            config_sdk_version: The Verify Push SDK version used to configure the factor
            config_time_step: Defines how often, in seconds, are TOTP codes generated. i.e, a new TOTP code is generated
                every time_step seconds. Must be between 20 and 60 seconds, inclusive
            config_skew: The number of time-steps, past and future, that are valid for validation of TOTP codes. Must be
                between 0 and 2, inclusive
            config_code_length: Number of digits for generated TOTP codes. Must be between 3 and 8, inclusive
            config_alg: Value sent with the request.
            config_notification_platform: The transport technology used to generate the Notification Token. Can be
                ``apn``, ``fcm`` or ``none``. Required when ``factor_type`` is ``push``.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.update_factor(
            service_sid,
            identity,
            sid,
            auth_payload=auth_payload,
            friendly_name=friendly_name,
            config_notification_token=config_notification_token,
            config_sdk_version=config_sdk_version,
            config_time_step=config_time_step,
            config_skew=config_skew,
            config_code_length=config_code_length,
            config_alg=config_alg,
            config_notification_platform=config_notification_platform,
            request_options=request_options,
        ).unwrap()

    @property
    def with_raw_response(self) -> VerifyV2FactorWithRawResponse:
        return self._with_raw_response


class AsyncVerifyV2Factor:
    def __init__(self, client: AsyncRawClient, server: Server, auth: AsyncAuthSchemes) -> None:
        self._with_raw_response = AsyncVerifyV2FactorWithRawResponse(client, server, auth)

    async def delete_factor(
        self, service_sid: str, identity: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> None:
        """Delete a specific Factor.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Factor. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            sid: A 34 character string that uniquely identifies this Factor.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            The resource was deleted successfully.

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (
            await self._with_raw_response.delete_factor(service_sid, identity, sid, request_options=request_options)
        ).unwrap()

    async def fetch_factor(
        self, service_sid: str, identity: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> VerifyV2ServiceEntityFactor:
        """Fetch a specific Factor.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Factor. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            sid: A 34 character string that uniquely identifies this Factor.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (
            await self._with_raw_response.fetch_factor(service_sid, identity, sid, request_options=request_options)
        ).unwrap()

    async def list_factor(
        self,
        service_sid: str,
        identity: str,
        *,
        page_size: int | None = None,
        page: int | None = None,
        page_token: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ListFactorResponse:
        """Retrieve a list of all Factors for an Entity.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Factors. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            page_size: How many resources to return in each list page. The default is 50, and the maximum is 1000.
            page: The page index. This value is simply for client state.
            page_token: The page token. This is provided by the API.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (
            await self._with_raw_response.list_factor(
                service_sid,
                identity,
                page_size=page_size,
                page=page,
                page_token=page_token,
                request_options=request_options,
            )
        ).unwrap()

    async def update_factor(
        self,
        service_sid: str,
        identity: str,
        sid: str,
        *,
        auth_payload: str | None = None,
        friendly_name: str | None = None,
        config_notification_token: str | None = None,
        config_sdk_version: str | None = None,
        config_time_step: int | None = None,
        config_skew: int | None = None,
        config_code_length: int | None = None,
        config_alg: FactorEnumTotpAlgorithmsOrStr | None = None,
        config_notification_platform: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> VerifyV2ServiceEntityFactor:
        """Update a specific Factor. This endpoint can be used to Verify a Factor if passed an ``AuthPayload`` param.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Factor. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            sid: A 34 character string that uniquely identifies this Factor.
            auth_payload: The optional payload needed to verify the Factor for the first time. E.g. for a TOTP, the
                numeric code.
            friendly_name: The new friendly name of this Factor. It can be up to 64 characters.
            config_notification_token: For APN, the device token. For FCM, the registration token. It is used to send
                the push notifications. Required when ``factor_type`` is ``push``. If specified, this value must be
                between 32 and 255 characters long.
            config_sdk_version: The Verify Push SDK version used to configure the factor
            config_time_step: Defines how often, in seconds, are TOTP codes generated. i.e, a new TOTP code is generated
                every time_step seconds. Must be between 20 and 60 seconds, inclusive
            config_skew: The number of time-steps, past and future, that are valid for validation of TOTP codes. Must be
                between 0 and 2, inclusive
            config_code_length: Number of digits for generated TOTP codes. Must be between 3 and 8, inclusive
            config_alg: Value sent with the request.
            config_notification_platform: The transport technology used to generate the Notification Token. Can be
                ``apn``, ``fcm`` or ``none``. Required when ``factor_type`` is ``push``.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (
            await self._with_raw_response.update_factor(
                service_sid,
                identity,
                sid,
                auth_payload=auth_payload,
                friendly_name=friendly_name,
                config_notification_token=config_notification_token,
                config_sdk_version=config_sdk_version,
                config_time_step=config_time_step,
                config_skew=config_skew,
                config_code_length=config_code_length,
                config_alg=config_alg,
                config_notification_platform=config_notification_platform,
                request_options=request_options,
            )
        ).unwrap()

    @property
    def with_raw_response(self) -> AsyncVerifyV2FactorWithRawResponse:
        return self._with_raw_response


class VerifyV2FactorWithRawResponse(SecuredRawResponse[RawClient, Server, AuthSchemes]):
    def delete_factor(
        self, service_sid: str, identity: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> ApiResult[None, RawError]:
        """Delete a specific Factor.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Factor. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            sid: A 34 character string that uniquely identifies this Factor.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="DELETE",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Factors/{Sid}"),
            path_params=[
                param[str]("ServiceSid", service_sid), param[str]("Identity", identity), param[str]("Sid", sid)
            ],
            headers=[param[UUID]("Idempotency-Key", uuid4())],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=empty_response,
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    def fetch_factor(
        self, service_sid: str, identity: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> ApiResult[VerifyV2ServiceEntityFactor, RawError]:
        """Fetch a specific Factor.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Factor. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            sid: A 34 character string that uniquely identifies this Factor.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="GET",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Factors/{Sid}"),
            path_params=[
                param[str]("ServiceSid", service_sid), param[str]("Identity", identity), param[str]("Sid", sid)
            ],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[VerifyV2ServiceEntityFactor],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    def list_factor(
        self,
        service_sid: str,
        identity: str,
        *,
        page_size: int | None = None,
        page: int | None = None,
        page_token: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[ListFactorResponse, RawError]:
        """Retrieve a list of all Factors for an Entity.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Factors. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            page_size: How many resources to return in each list page. The default is 50, and the maximum is 1000.
            page: The page index. This value is simply for client state.
            page_token: The page token. This is provided by the API.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="GET",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Factors"),
            path_params=[param[str]("ServiceSid", service_sid), param[str]("Identity", identity)],
            query_params=[
                param[int | None]("PageSize", page_size),
                param[int | None]("Page", page),
                param[str | None]("PageToken", page_token),
            ],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[ListFactorResponse],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    def update_factor(
        self,
        service_sid: str,
        identity: str,
        sid: str,
        *,
        auth_payload: str | None = None,
        friendly_name: str | None = None,
        config_notification_token: str | None = None,
        config_sdk_version: str | None = None,
        config_time_step: int | None = None,
        config_skew: int | None = None,
        config_code_length: int | None = None,
        config_alg: FactorEnumTotpAlgorithmsOrStr | None = None,
        config_notification_platform: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[VerifyV2ServiceEntityFactor, RawError]:
        """Update a specific Factor. This endpoint can be used to Verify a Factor if passed an ``AuthPayload`` param.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Factor. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            sid: A 34 character string that uniquely identifies this Factor.
            auth_payload: The optional payload needed to verify the Factor for the first time. E.g. for a TOTP, the
                numeric code.
            friendly_name: The new friendly name of this Factor. It can be up to 64 characters.
            config_notification_token: For APN, the device token. For FCM, the registration token. It is used to send
                the push notifications. Required when ``factor_type`` is ``push``. If specified, this value must be
                between 32 and 255 characters long.
            config_sdk_version: The Verify Push SDK version used to configure the factor
            config_time_step: Defines how often, in seconds, are TOTP codes generated. i.e, a new TOTP code is generated
                every time_step seconds. Must be between 20 and 60 seconds, inclusive
            config_skew: The number of time-steps, past and future, that are valid for validation of TOTP codes. Must be
                between 0 and 2, inclusive
            config_code_length: Number of digits for generated TOTP codes. Must be between 3 and 8, inclusive
            config_alg: Value sent with the request.
            config_notification_platform: The transport technology used to generate the Notification Token. Can be
                ``apn``, ``fcm`` or ``none``. Required when ``factor_type`` is ``push``.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="POST",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Factors/{Sid}"),
            path_params=[
                param[str]("ServiceSid", service_sid), param[str]("Identity", identity), param[str]("Sid", sid)
            ],
            headers=[param[UUID]("Idempotency-Key", uuid4())],
            body=form_body(
                [
                    param[str | None]("AuthPayload", auth_payload),
                    param[str | None]("FriendlyName", friendly_name),
                    param[str | None]("Config.NotificationToken", config_notification_token),
                    param[str | None]("Config.SdkVersion", config_sdk_version),
                    param[int | None]("Config.TimeStep", config_time_step),
                    param[int | None]("Config.Skew", config_skew),
                    param[int | None]("Config.CodeLength", config_code_length),
                    param[FactorEnumTotpAlgorithmsOrStr | None]("Config.Alg", config_alg),
                    param[str | None]("Config.NotificationPlatform", config_notification_platform),
                ],
            ),
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[VerifyV2ServiceEntityFactor],
            error_mapper=raw_error_response,
            request_options=request_options,
        )


class AsyncVerifyV2FactorWithRawResponse(SecuredRawResponse[AsyncRawClient, Server, AsyncAuthSchemes]):
    async def delete_factor(
        self, service_sid: str, identity: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> ApiResult[None, RawError]:
        """Delete a specific Factor.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Factor. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            sid: A 34 character string that uniquely identifies this Factor.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="DELETE",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Factors/{Sid}"),
            path_params=[
                param[str]("ServiceSid", service_sid), param[str]("Identity", identity), param[str]("Sid", sid)
            ],
            headers=[param[UUID]("Idempotency-Key", uuid4())],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=empty_response,
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    async def fetch_factor(
        self, service_sid: str, identity: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> ApiResult[VerifyV2ServiceEntityFactor, RawError]:
        """Fetch a specific Factor.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Factor. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            sid: A 34 character string that uniquely identifies this Factor.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="GET",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Factors/{Sid}"),
            path_params=[
                param[str]("ServiceSid", service_sid), param[str]("Identity", identity), param[str]("Sid", sid)
            ],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[VerifyV2ServiceEntityFactor],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    async def list_factor(
        self,
        service_sid: str,
        identity: str,
        *,
        page_size: int | None = None,
        page: int | None = None,
        page_token: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[ListFactorResponse, RawError]:
        """Retrieve a list of all Factors for an Entity.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Factors. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            page_size: How many resources to return in each list page. The default is 50, and the maximum is 1000.
            page: The page index. This value is simply for client state.
            page_token: The page token. This is provided by the API.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="GET",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Factors"),
            path_params=[param[str]("ServiceSid", service_sid), param[str]("Identity", identity)],
            query_params=[
                param[int | None]("PageSize", page_size),
                param[int | None]("Page", page),
                param[str | None]("PageToken", page_token),
            ],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[ListFactorResponse],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    async def update_factor(
        self,
        service_sid: str,
        identity: str,
        sid: str,
        *,
        auth_payload: str | None = None,
        friendly_name: str | None = None,
        config_notification_token: str | None = None,
        config_sdk_version: str | None = None,
        config_time_step: int | None = None,
        config_skew: int | None = None,
        config_code_length: int | None = None,
        config_alg: FactorEnumTotpAlgorithmsOrStr | None = None,
        config_notification_platform: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[VerifyV2ServiceEntityFactor, RawError]:
        """Update a specific Factor. This endpoint can be used to Verify a Factor if passed an ``AuthPayload`` param.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Factor. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            sid: A 34 character string that uniquely identifies this Factor.
            auth_payload: The optional payload needed to verify the Factor for the first time. E.g. for a TOTP, the
                numeric code.
            friendly_name: The new friendly name of this Factor. It can be up to 64 characters.
            config_notification_token: For APN, the device token. For FCM, the registration token. It is used to send
                the push notifications. Required when ``factor_type`` is ``push``. If specified, this value must be
                between 32 and 255 characters long.
            config_sdk_version: The Verify Push SDK version used to configure the factor
            config_time_step: Defines how often, in seconds, are TOTP codes generated. i.e, a new TOTP code is generated
                every time_step seconds. Must be between 20 and 60 seconds, inclusive
            config_skew: The number of time-steps, past and future, that are valid for validation of TOTP codes. Must be
                between 0 and 2, inclusive
            config_code_length: Number of digits for generated TOTP codes. Must be between 3 and 8, inclusive
            config_alg: Value sent with the request.
            config_notification_platform: The transport technology used to generate the Notification Token. Can be
                ``apn``, ``fcm`` or ``none``. Required when ``factor_type`` is ``push``.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="POST",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Factors/{Sid}"),
            path_params=[
                param[str]("ServiceSid", service_sid), param[str]("Identity", identity), param[str]("Sid", sid)
            ],
            headers=[param[UUID]("Idempotency-Key", uuid4())],
            body=form_body(
                [
                    param[str | None]("AuthPayload", auth_payload),
                    param[str | None]("FriendlyName", friendly_name),
                    param[str | None]("Config.NotificationToken", config_notification_token),
                    param[str | None]("Config.SdkVersion", config_sdk_version),
                    param[int | None]("Config.TimeStep", config_time_step),
                    param[int | None]("Config.Skew", config_skew),
                    param[int | None]("Config.CodeLength", config_code_length),
                    param[FactorEnumTotpAlgorithmsOrStr | None]("Config.Alg", config_alg),
                    param[str | None]("Config.NotificationPlatform", config_notification_platform),
                ],
            ),
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[VerifyV2ServiceEntityFactor],
            error_mapper=raw_error_response,
            request_options=request_options,
        )
