from __future__ import annotations

from typing import Any

from ..auth import AsyncAuthSchemes, AuthSchemes
from ..core import (
    ApiResult,
    AsyncRawClient,
    RawClient,
    RawError,
    RequestOptionsOrDict,
    RFC3339DateTime,
    SecuredRawResponse,
    form_body,
    json_decoder,
    param,
    raw_error_response,
)
from ..models.enums.challenge_enum_challenge_statuses import ChallengeEnumChallengeStatusesOrStr
from ..models.enums.challenge_enum_list_orders import ChallengeEnumListOrdersOrStr
from ..models.list_challenge_response import ListChallengeResponse
from ..models.verify_v2_service_entity_challenge import VerifyV2ServiceEntityChallenge
from ..server.server import Server


class VerifyV2Challenge:
    def __init__(self, client: RawClient, server: Server, auth: AuthSchemes) -> None:
        self._with_raw_response = VerifyV2ChallengeWithRawResponse(client, server, auth)

    def create_challenge(
        self,
        service_sid: str,
        identity: str,
        factor_sid: str,
        *,
        expiration_date: RFC3339DateTime | None = None,
        details_message: str | None = None,
        details_fields: list[Any] | None = None,
        hidden_details: Any | None = None,
        auth_payload: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> VerifyV2ServiceEntityChallenge:
        """Create a new Challenge for the Factor

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Challenge. This identifier should be
                immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as
                your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            factor_sid: The unique SID identifier of the Factor.
            expiration_date: The date-time when this Challenge expires, given in `ISO 8601
                <https://en.wikipedia.org/wiki/ISO_8601>`__ format. The default value is five (5) minutes after
                Challenge creation. The max value is sixty (60) minutes after creation.
            details_message: Shown to the user when the push notification arrives. Required when ``factor_type`` is
                ``push``. Can be up to 256 characters in length
            details_fields: A list of objects that describe the Fields included in the Challenge. Each object contains
                the label and value of the field, the label can be up to 36 characters in length and the value can be up
                to 128 characters in length. Used when ``factor_type`` is ``push``. There can be up to 20 details
                fields.
            hidden_details: Details provided to give context about the Challenge. Not shown to the end user. It must be
                a stringified JSON with only strings values eg. ``{"ip": "172.168.1.234"}``. Can be up to 1024
                characters in length
            auth_payload: Optional payload used to verify the Challenge upon creation. Only used with a Factor of type
                ``totp`` to carry the TOTP code that needs to be verified. For ``TOTP`` this value must be between 3 and
                8 characters long.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            Created

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.create_challenge(
            service_sid,
            identity,
            factor_sid,
            expiration_date=expiration_date,
            details_message=details_message,
            details_fields=details_fields,
            hidden_details=hidden_details,
            auth_payload=auth_payload,
            request_options=request_options,
        ).unwrap()

    def fetch_challenge(
        self, service_sid: str, identity: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> VerifyV2ServiceEntityChallenge:
        """Fetch a specific Challenge.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Challenges. This identifier should be
                immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as
                your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            sid: A 34 character string that uniquely identifies this Challenge.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.fetch_challenge(
            service_sid, identity, sid, request_options=request_options
        ).unwrap()

    def list_challenge(
        self,
        service_sid: str,
        identity: str,
        *,
        factor_sid: str | None = None,
        status: ChallengeEnumChallengeStatusesOrStr | None = None,
        order: ChallengeEnumListOrdersOrStr | None = None,
        page_size: int | None = None,
        page: int | None = None,
        page_token: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ListChallengeResponse:
        """Retrieve a list of all Challenges for a Factor.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Challenge. This identifier should be
                immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as
                your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            factor_sid: The unique SID identifier of the Factor.
            status: The Status of the Challenges to fetch. One of ``pending``, ``expired``, ``approved`` or ``denied``.
            order: The desired sort order of the Challenges list. One of ``asc`` or ``desc`` for ascending and
                descending respectively. Defaults to ``asc``.
            page_size: How many resources to return in each list page. The default is 50, and the maximum is 1000.
            page: The page index. This value is simply for client state.
            page_token: The page token. This is provided by the API.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.list_challenge(
            service_sid,
            identity,
            factor_sid=factor_sid,
            status=status,
            order=order,
            page_size=page_size,
            page=page,
            page_token=page_token,
            request_options=request_options,
        ).unwrap()

    def update_challenge(
        self,
        service_sid: str,
        identity: str,
        sid: str,
        *,
        auth_payload: str | None = None,
        metadata: Any | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> VerifyV2ServiceEntityChallenge:
        """Verify a specific Challenge.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Challenge. This identifier should be
                immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as
                your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            sid: A 34 character string that uniquely identifies this Challenge.
            auth_payload: The optional payload needed to verify the Challenge. E.g., a TOTP would use the numeric code.
                For ``TOTP`` this value must be between 3 and 8 characters long. For ``Push`` this value can be up to
                5456 characters in length
            metadata: Custom metadata associated with the challenge. This is added by the Device/SDK directly to allow
                for the inclusion of device information. It must be a stringified JSON with only strings values eg.
                ``{"os": "Android"}``. Can be up to 1024 characters in length.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.update_challenge(
            service_sid, identity, sid, auth_payload=auth_payload, metadata=metadata, request_options=request_options
        ).unwrap()

    @property
    def with_raw_response(self) -> VerifyV2ChallengeWithRawResponse:
        return self._with_raw_response


class AsyncVerifyV2Challenge:
    def __init__(self, client: AsyncRawClient, server: Server, auth: AsyncAuthSchemes) -> None:
        self._with_raw_response = AsyncVerifyV2ChallengeWithRawResponse(client, server, auth)

    async def create_challenge(
        self,
        service_sid: str,
        identity: str,
        factor_sid: str,
        *,
        expiration_date: RFC3339DateTime | None = None,
        details_message: str | None = None,
        details_fields: list[Any] | None = None,
        hidden_details: Any | None = None,
        auth_payload: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> VerifyV2ServiceEntityChallenge:
        """Create a new Challenge for the Factor

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Challenge. This identifier should be
                immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as
                your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            factor_sid: The unique SID identifier of the Factor.
            expiration_date: The date-time when this Challenge expires, given in `ISO 8601
                <https://en.wikipedia.org/wiki/ISO_8601>`__ format. The default value is five (5) minutes after
                Challenge creation. The max value is sixty (60) minutes after creation.
            details_message: Shown to the user when the push notification arrives. Required when ``factor_type`` is
                ``push``. Can be up to 256 characters in length
            details_fields: A list of objects that describe the Fields included in the Challenge. Each object contains
                the label and value of the field, the label can be up to 36 characters in length and the value can be up
                to 128 characters in length. Used when ``factor_type`` is ``push``. There can be up to 20 details
                fields.
            hidden_details: Details provided to give context about the Challenge. Not shown to the end user. It must be
                a stringified JSON with only strings values eg. ``{"ip": "172.168.1.234"}``. Can be up to 1024
                characters in length
            auth_payload: Optional payload used to verify the Challenge upon creation. Only used with a Factor of type
                ``totp`` to carry the TOTP code that needs to be verified. For ``TOTP`` this value must be between 3 and
                8 characters long.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            Created

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (
            await self._with_raw_response.create_challenge(
                service_sid,
                identity,
                factor_sid,
                expiration_date=expiration_date,
                details_message=details_message,
                details_fields=details_fields,
                hidden_details=hidden_details,
                auth_payload=auth_payload,
                request_options=request_options,
            )
        ).unwrap()

    async def fetch_challenge(
        self, service_sid: str, identity: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> VerifyV2ServiceEntityChallenge:
        """Fetch a specific Challenge.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Challenges. This identifier should be
                immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as
                your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            sid: A 34 character string that uniquely identifies this Challenge.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (
            await self._with_raw_response.fetch_challenge(service_sid, identity, sid, request_options=request_options)
        ).unwrap()

    async def list_challenge(
        self,
        service_sid: str,
        identity: str,
        *,
        factor_sid: str | None = None,
        status: ChallengeEnumChallengeStatusesOrStr | None = None,
        order: ChallengeEnumListOrdersOrStr | None = None,
        page_size: int | None = None,
        page: int | None = None,
        page_token: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ListChallengeResponse:
        """Retrieve a list of all Challenges for a Factor.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Challenge. This identifier should be
                immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as
                your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            factor_sid: The unique SID identifier of the Factor.
            status: The Status of the Challenges to fetch. One of ``pending``, ``expired``, ``approved`` or ``denied``.
            order: The desired sort order of the Challenges list. One of ``asc`` or ``desc`` for ascending and
                descending respectively. Defaults to ``asc``.
            page_size: How many resources to return in each list page. The default is 50, and the maximum is 1000.
            page: The page index. This value is simply for client state.
            page_token: The page token. This is provided by the API.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (
            await self._with_raw_response.list_challenge(
                service_sid,
                identity,
                factor_sid=factor_sid,
                status=status,
                order=order,
                page_size=page_size,
                page=page,
                page_token=page_token,
                request_options=request_options,
            )
        ).unwrap()

    async def update_challenge(
        self,
        service_sid: str,
        identity: str,
        sid: str,
        *,
        auth_payload: str | None = None,
        metadata: Any | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> VerifyV2ServiceEntityChallenge:
        """Verify a specific Challenge.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Challenge. This identifier should be
                immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as
                your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            sid: A 34 character string that uniquely identifies this Challenge.
            auth_payload: The optional payload needed to verify the Challenge. E.g., a TOTP would use the numeric code.
                For ``TOTP`` this value must be between 3 and 8 characters long. For ``Push`` this value can be up to
                5456 characters in length
            metadata: Custom metadata associated with the challenge. This is added by the Device/SDK directly to allow
                for the inclusion of device information. It must be a stringified JSON with only strings values eg.
                ``{"os": "Android"}``. Can be up to 1024 characters in length.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (
            await self._with_raw_response.update_challenge(
                service_sid,
                identity,
                sid,
                auth_payload=auth_payload,
                metadata=metadata,
                request_options=request_options,
            )
        ).unwrap()

    @property
    def with_raw_response(self) -> AsyncVerifyV2ChallengeWithRawResponse:
        return self._with_raw_response


class VerifyV2ChallengeWithRawResponse(SecuredRawResponse[RawClient, Server, AuthSchemes]):
    def create_challenge(
        self,
        service_sid: str,
        identity: str,
        factor_sid: str,
        *,
        expiration_date: RFC3339DateTime | None = None,
        details_message: str | None = None,
        details_fields: list[Any] | None = None,
        hidden_details: Any | None = None,
        auth_payload: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[VerifyV2ServiceEntityChallenge, RawError]:
        """Create a new Challenge for the Factor

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Challenge. This identifier should be
                immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as
                your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            factor_sid: The unique SID identifier of the Factor.
            expiration_date: The date-time when this Challenge expires, given in `ISO 8601
                <https://en.wikipedia.org/wiki/ISO_8601>`__ format. The default value is five (5) minutes after
                Challenge creation. The max value is sixty (60) minutes after creation.
            details_message: Shown to the user when the push notification arrives. Required when ``factor_type`` is
                ``push``. Can be up to 256 characters in length
            details_fields: A list of objects that describe the Fields included in the Challenge. Each object contains
                the label and value of the field, the label can be up to 36 characters in length and the value can be up
                to 128 characters in length. Used when ``factor_type`` is ``push``. There can be up to 20 details
                fields.
            hidden_details: Details provided to give context about the Challenge. Not shown to the end user. It must be
                a stringified JSON with only strings values eg. ``{"ip": "172.168.1.234"}``. Can be up to 1024
                characters in length
            auth_payload: Optional payload used to verify the Challenge upon creation. Only used with a Factor of type
                ``totp`` to carry the TOTP code that needs to be verified. For ``TOTP`` this value must be between 3 and
                8 characters long.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="POST",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Challenges"),
            path_params=[param[str]("ServiceSid", service_sid), param[str]("Identity", identity)],
            body=form_body(
                [
                    param[str]("FactorSid", factor_sid),
                    param[RFC3339DateTime | None]("ExpirationDate", expiration_date),
                    param[str | None]("Details.Message", details_message),
                    param[list[Any] | None]("Details.Fields", details_fields),
                    param[Any | None]("HiddenDetails", hidden_details),
                    param[str | None]("AuthPayload", auth_payload),
                ],
            ),
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[VerifyV2ServiceEntityChallenge],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    def fetch_challenge(
        self, service_sid: str, identity: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> ApiResult[VerifyV2ServiceEntityChallenge, RawError]:
        """Fetch a specific Challenge.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Challenges. This identifier should be
                immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as
                your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            sid: A 34 character string that uniquely identifies this Challenge.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="GET",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Challenges/{Sid}"),
            path_params=[
                param[str]("ServiceSid", service_sid), param[str]("Identity", identity), param[str]("Sid", sid)
            ],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[VerifyV2ServiceEntityChallenge],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    def list_challenge(
        self,
        service_sid: str,
        identity: str,
        *,
        factor_sid: str | None = None,
        status: ChallengeEnumChallengeStatusesOrStr | None = None,
        order: ChallengeEnumListOrdersOrStr | None = None,
        page_size: int | None = None,
        page: int | None = None,
        page_token: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[ListChallengeResponse, RawError]:
        """Retrieve a list of all Challenges for a Factor.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Challenge. This identifier should be
                immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as
                your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            factor_sid: The unique SID identifier of the Factor.
            status: The Status of the Challenges to fetch. One of ``pending``, ``expired``, ``approved`` or ``denied``.
            order: The desired sort order of the Challenges list. One of ``asc`` or ``desc`` for ascending and
                descending respectively. Defaults to ``asc``.
            page_size: How many resources to return in each list page. The default is 50, and the maximum is 1000.
            page: The page index. This value is simply for client state.
            page_token: The page token. This is provided by the API.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="GET",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Challenges"),
            path_params=[param[str]("ServiceSid", service_sid), param[str]("Identity", identity)],
            query_params=[
                param[str | None]("FactorSid", factor_sid),
                param[ChallengeEnumChallengeStatusesOrStr | None]("Status", status),
                param[ChallengeEnumListOrdersOrStr | None]("Order", order),
                param[int | None]("PageSize", page_size),
                param[int | None]("Page", page),
                param[str | None]("PageToken", page_token),
            ],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[ListChallengeResponse],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    def update_challenge(
        self,
        service_sid: str,
        identity: str,
        sid: str,
        *,
        auth_payload: str | None = None,
        metadata: Any | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[VerifyV2ServiceEntityChallenge, RawError]:
        """Verify a specific Challenge.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Challenge. This identifier should be
                immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as
                your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            sid: A 34 character string that uniquely identifies this Challenge.
            auth_payload: The optional payload needed to verify the Challenge. E.g., a TOTP would use the numeric code.
                For ``TOTP`` this value must be between 3 and 8 characters long. For ``Push`` this value can be up to
                5456 characters in length
            metadata: Custom metadata associated with the challenge. This is added by the Device/SDK directly to allow
                for the inclusion of device information. It must be a stringified JSON with only strings values eg.
                ``{"os": "Android"}``. Can be up to 1024 characters in length.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="POST",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Challenges/{Sid}"),
            path_params=[
                param[str]("ServiceSid", service_sid), param[str]("Identity", identity), param[str]("Sid", sid)
            ],
            body=form_body([param[str | None]("AuthPayload", auth_payload), param[Any | None]("Metadata", metadata)]),
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[VerifyV2ServiceEntityChallenge],
            error_mapper=raw_error_response,
            request_options=request_options,
        )


class AsyncVerifyV2ChallengeWithRawResponse(SecuredRawResponse[AsyncRawClient, Server, AsyncAuthSchemes]):
    async def create_challenge(
        self,
        service_sid: str,
        identity: str,
        factor_sid: str,
        *,
        expiration_date: RFC3339DateTime | None = None,
        details_message: str | None = None,
        details_fields: list[Any] | None = None,
        hidden_details: Any | None = None,
        auth_payload: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[VerifyV2ServiceEntityChallenge, RawError]:
        """Create a new Challenge for the Factor

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Challenge. This identifier should be
                immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as
                your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            factor_sid: The unique SID identifier of the Factor.
            expiration_date: The date-time when this Challenge expires, given in `ISO 8601
                <https://en.wikipedia.org/wiki/ISO_8601>`__ format. The default value is five (5) minutes after
                Challenge creation. The max value is sixty (60) minutes after creation.
            details_message: Shown to the user when the push notification arrives. Required when ``factor_type`` is
                ``push``. Can be up to 256 characters in length
            details_fields: A list of objects that describe the Fields included in the Challenge. Each object contains
                the label and value of the field, the label can be up to 36 characters in length and the value can be up
                to 128 characters in length. Used when ``factor_type`` is ``push``. There can be up to 20 details
                fields.
            hidden_details: Details provided to give context about the Challenge. Not shown to the end user. It must be
                a stringified JSON with only strings values eg. ``{"ip": "172.168.1.234"}``. Can be up to 1024
                characters in length
            auth_payload: Optional payload used to verify the Challenge upon creation. Only used with a Factor of type
                ``totp`` to carry the TOTP code that needs to be verified. For ``TOTP`` this value must be between 3 and
                8 characters long.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="POST",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Challenges"),
            path_params=[param[str]("ServiceSid", service_sid), param[str]("Identity", identity)],
            body=form_body(
                [
                    param[str]("FactorSid", factor_sid),
                    param[RFC3339DateTime | None]("ExpirationDate", expiration_date),
                    param[str | None]("Details.Message", details_message),
                    param[list[Any] | None]("Details.Fields", details_fields),
                    param[Any | None]("HiddenDetails", hidden_details),
                    param[str | None]("AuthPayload", auth_payload),
                ],
            ),
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[VerifyV2ServiceEntityChallenge],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    async def fetch_challenge(
        self, service_sid: str, identity: str, sid: str, *, request_options: RequestOptionsOrDict | None = None
    ) -> ApiResult[VerifyV2ServiceEntityChallenge, RawError]:
        """Fetch a specific Challenge.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Challenges. This identifier should be
                immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as
                your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            sid: A 34 character string that uniquely identifies this Challenge.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="GET",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Challenges/{Sid}"),
            path_params=[
                param[str]("ServiceSid", service_sid), param[str]("Identity", identity), param[str]("Sid", sid)
            ],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[VerifyV2ServiceEntityChallenge],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    async def list_challenge(
        self,
        service_sid: str,
        identity: str,
        *,
        factor_sid: str | None = None,
        status: ChallengeEnumChallengeStatusesOrStr | None = None,
        order: ChallengeEnumListOrdersOrStr | None = None,
        page_size: int | None = None,
        page: int | None = None,
        page_token: str | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[ListChallengeResponse, RawError]:
        """Retrieve a list of all Challenges for a Factor.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Challenge. This identifier should be
                immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as
                your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            factor_sid: The unique SID identifier of the Factor.
            status: The Status of the Challenges to fetch. One of ``pending``, ``expired``, ``approved`` or ``denied``.
            order: The desired sort order of the Challenges list. One of ``asc`` or ``desc`` for ascending and
                descending respectively. Defaults to ``asc``.
            page_size: How many resources to return in each list page. The default is 50, and the maximum is 1000.
            page: The page index. This value is simply for client state.
            page_token: The page token. This is provided by the API.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="GET",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Challenges"),
            path_params=[param[str]("ServiceSid", service_sid), param[str]("Identity", identity)],
            query_params=[
                param[str | None]("FactorSid", factor_sid),
                param[ChallengeEnumChallengeStatusesOrStr | None]("Status", status),
                param[ChallengeEnumListOrdersOrStr | None]("Order", order),
                param[int | None]("PageSize", page_size),
                param[int | None]("Page", page),
                param[str | None]("PageToken", page_token),
            ],
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[ListChallengeResponse],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    async def update_challenge(
        self,
        service_sid: str,
        identity: str,
        sid: str,
        *,
        auth_payload: str | None = None,
        metadata: Any | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[VerifyV2ServiceEntityChallenge, RawError]:
        """Verify a specific Challenge.

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Challenge. This identifier should be
                immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as
                your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            sid: A 34 character string that uniquely identifies this Challenge.
            auth_payload: The optional payload needed to verify the Challenge. E.g., a TOTP would use the numeric code.
                For ``TOTP`` this value must be between 3 and 8 characters long. For ``Push`` this value can be up to
                5456 characters in length
            metadata: Custom metadata associated with the challenge. This is added by the Device/SDK directly to allow
                for the inclusion of device information. It must be a stringified JSON with only strings values eg.
                ``{"os": "Android"}``. Can be up to 1024 characters in length.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="POST",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Challenges/{Sid}"),
            path_params=[
                param[str]("ServiceSid", service_sid), param[str]("Identity", identity), param[str]("Sid", sid)
            ],
            body=form_body([param[str | None]("AuthPayload", auth_payload), param[Any | None]("Metadata", metadata)]),
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[VerifyV2ServiceEntityChallenge],
            error_mapper=raw_error_response,
            request_options=request_options,
        )
