from __future__ import annotations

from typing import Any
from uuid import UUID, uuid4

from ..auth import AsyncAuthSchemes, AuthSchemes
from ..core import (
    ApiResult,
    AsyncRawClient,
    RawClient,
    RawError,
    RequestOptionsOrDict,
    SecuredRawResponse,
    form_body,
    json_body,
    json_decoder,
    param,
    raw_error_response,
)
from ..models.create_new_passkeys_factor_request import (
    CreateNewPasskeysFactorRequest,
    CreateNewPasskeysFactorRequestDict,
)
from ..models.enums.new_factor_enum_factor_types import NewFactorEnumFactorTypesOrStr
from ..models.enums.new_factor_enum_notification_platforms import NewFactorEnumNotificationPlatformsOrStr
from ..models.enums.new_factor_enum_totp_algorithms import NewFactorEnumTotpAlgorithmsOrStr
from ..models.v2_services_passkeys_factors_response import V2ServicesPasskeysFactorsResponse
from ..models.verify_v2_service_entity_new_factor import VerifyV2ServiceEntityNewFactor
from ..server.server import Server


class VerifyV2NewFactor:
    def __init__(self, client: RawClient, server: Server, auth: AuthSchemes) -> None:
        self._with_raw_response = VerifyV2NewFactorWithRawResponse(client, server, auth)

    def create_new_factor(
        self,
        service_sid: str,
        identity: str,
        friendly_name: str,
        factor_type: NewFactorEnumFactorTypesOrStr,
        *,
        binding_alg: str | None = None,
        binding_public_key: str | None = None,
        config_app_id: str | None = None,
        config_notification_platform: NewFactorEnumNotificationPlatformsOrStr | None = None,
        config_notification_token: str | None = None,
        config_sdk_version: str | None = None,
        binding_secret: str | None = None,
        config_time_step: int | None = None,
        config_skew: int | None = None,
        config_code_length: int | None = None,
        config_alg: NewFactorEnumTotpAlgorithmsOrStr | None = None,
        metadata: Any | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> VerifyV2ServiceEntityNewFactor:
        """Create a new Factor for the Entity

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Factor. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            friendly_name: The friendly name of this Factor. This can be any string up to 64 characters, meant for
                humans to distinguish between Factors. For ``factor_type`` ``push``, this could be a device name. For
                ``factor_type`` ``totp``, this value is used as the “account name” in constructing the ``binding.uri``
                property. At the same time, we recommend avoiding providing PII.
            factor_type: The Type of this Factor. Currently ``push`` and ``totp`` are supported.
            binding_alg: The algorithm used when ``factor_type`` is ``push``. Algorithm supported: ``ES256``
            binding_public_key: The Ecdsa public key in PKIX, ASN.1 DER format encoded in Base64. Required when
                ``factor_type`` is ``push``
            config_app_id: The ID that uniquely identifies your app in the Google or Apple store, such as
                ``com.example.myapp``. It can be up to 100 characters long. Required when ``factor_type`` is ``push``.
            config_notification_platform: Value sent with the request.
            config_notification_token: For APN, the device token. For FCM, the registration token. It is used to send
                the push notifications. Must be between 32 and 255 characters long. Required when ``factor_type`` is
                ``push``.
            config_sdk_version: The Verify Push SDK version used to configure the factor Required when ``factor_type``
                is ``push``
            binding_secret: The shared secret for TOTP factors encoded in Base32. This can be provided when creating the
                Factor, otherwise it will be generated. Used when ``factor_type`` is ``totp``
            config_time_step: Defines how often, in seconds, are TOTP codes generated. i.e, a new TOTP code is generated
                every time_step seconds. Must be between 20 and 60 seconds, inclusive. The default value is defined at
                the service level in the property ``totp.time_step``. Defaults to 30 seconds if not configured. Used
                when ``factor_type`` is ``totp``
            config_skew: The number of time-steps, past and future, that are valid for validation of TOTP codes. Must be
                between 0 and 2, inclusive. The default value is defined at the service level in the property
                ``totp.skew``. If not configured defaults to 1. Used when ``factor_type`` is ``totp``
            config_code_length: Number of digits for generated TOTP codes. Must be between 3 and 8, inclusive. The
                default value is defined at the service level in the property ``totp.code_length``. If not configured
                defaults to 6. Used when ``factor_type`` is ``totp``
            config_alg: Value sent with the request.
            metadata: Custom metadata associated with the factor. This is added by the Device/SDK directly to allow for
                the inclusion of device information. It must be a stringified JSON with only strings values eg. ``{"os":
                "Android"}``. Can be up to 1024 characters in length.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            Created

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.create_new_factor(
            service_sid,
            identity,
            friendly_name,
            factor_type,
            binding_alg=binding_alg,
            binding_public_key=binding_public_key,
            config_app_id=config_app_id,
            config_notification_platform=config_notification_platform,
            config_notification_token=config_notification_token,
            config_sdk_version=config_sdk_version,
            binding_secret=binding_secret,
            config_time_step=config_time_step,
            config_skew=config_skew,
            config_code_length=config_code_length,
            config_alg=config_alg,
            metadata=metadata,
            request_options=request_options,
        ).unwrap()

    def create_new_factor_passkey(
        self,
        service_sid: str,
        body: CreateNewPasskeysFactorRequest | CreateNewPasskeysFactorRequestDict,
        *,
        request_options: RequestOptionsOrDict | None = None,
    ) -> V2ServicesPasskeysFactorsResponse:
        """Create a new Passkeys Factor for the Entity

        Args:
            service_sid: The unique SID identifier of the Service.
            body: The request body.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            Created

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.create_new_factor_passkey(
            service_sid, body, request_options=request_options
        ).unwrap()

    @property
    def with_raw_response(self) -> VerifyV2NewFactorWithRawResponse:
        return self._with_raw_response


class AsyncVerifyV2NewFactor:
    def __init__(self, client: AsyncRawClient, server: Server, auth: AsyncAuthSchemes) -> None:
        self._with_raw_response = AsyncVerifyV2NewFactorWithRawResponse(client, server, auth)

    async def create_new_factor(
        self,
        service_sid: str,
        identity: str,
        friendly_name: str,
        factor_type: NewFactorEnumFactorTypesOrStr,
        *,
        binding_alg: str | None = None,
        binding_public_key: str | None = None,
        config_app_id: str | None = None,
        config_notification_platform: NewFactorEnumNotificationPlatformsOrStr | None = None,
        config_notification_token: str | None = None,
        config_sdk_version: str | None = None,
        binding_secret: str | None = None,
        config_time_step: int | None = None,
        config_skew: int | None = None,
        config_code_length: int | None = None,
        config_alg: NewFactorEnumTotpAlgorithmsOrStr | None = None,
        metadata: Any | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> VerifyV2ServiceEntityNewFactor:
        """Create a new Factor for the Entity

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Factor. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            friendly_name: The friendly name of this Factor. This can be any string up to 64 characters, meant for
                humans to distinguish between Factors. For ``factor_type`` ``push``, this could be a device name. For
                ``factor_type`` ``totp``, this value is used as the “account name” in constructing the ``binding.uri``
                property. At the same time, we recommend avoiding providing PII.
            factor_type: The Type of this Factor. Currently ``push`` and ``totp`` are supported.
            binding_alg: The algorithm used when ``factor_type`` is ``push``. Algorithm supported: ``ES256``
            binding_public_key: The Ecdsa public key in PKIX, ASN.1 DER format encoded in Base64. Required when
                ``factor_type`` is ``push``
            config_app_id: The ID that uniquely identifies your app in the Google or Apple store, such as
                ``com.example.myapp``. It can be up to 100 characters long. Required when ``factor_type`` is ``push``.
            config_notification_platform: Value sent with the request.
            config_notification_token: For APN, the device token. For FCM, the registration token. It is used to send
                the push notifications. Must be between 32 and 255 characters long. Required when ``factor_type`` is
                ``push``.
            config_sdk_version: The Verify Push SDK version used to configure the factor Required when ``factor_type``
                is ``push``
            binding_secret: The shared secret for TOTP factors encoded in Base32. This can be provided when creating the
                Factor, otherwise it will be generated. Used when ``factor_type`` is ``totp``
            config_time_step: Defines how often, in seconds, are TOTP codes generated. i.e, a new TOTP code is generated
                every time_step seconds. Must be between 20 and 60 seconds, inclusive. The default value is defined at
                the service level in the property ``totp.time_step``. Defaults to 30 seconds if not configured. Used
                when ``factor_type`` is ``totp``
            config_skew: The number of time-steps, past and future, that are valid for validation of TOTP codes. Must be
                between 0 and 2, inclusive. The default value is defined at the service level in the property
                ``totp.skew``. If not configured defaults to 1. Used when ``factor_type`` is ``totp``
            config_code_length: Number of digits for generated TOTP codes. Must be between 3 and 8, inclusive. The
                default value is defined at the service level in the property ``totp.code_length``. If not configured
                defaults to 6. Used when ``factor_type`` is ``totp``
            config_alg: Value sent with the request.
            metadata: Custom metadata associated with the factor. This is added by the Device/SDK directly to allow for
                the inclusion of device information. It must be a stringified JSON with only strings values eg. ``{"os":
                "Android"}``. Can be up to 1024 characters in length.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            Created

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (
            await self._with_raw_response.create_new_factor(
                service_sid,
                identity,
                friendly_name,
                factor_type,
                binding_alg=binding_alg,
                binding_public_key=binding_public_key,
                config_app_id=config_app_id,
                config_notification_platform=config_notification_platform,
                config_notification_token=config_notification_token,
                config_sdk_version=config_sdk_version,
                binding_secret=binding_secret,
                config_time_step=config_time_step,
                config_skew=config_skew,
                config_code_length=config_code_length,
                config_alg=config_alg,
                metadata=metadata,
                request_options=request_options,
            )
        ).unwrap()

    async def create_new_factor_passkey(
        self,
        service_sid: str,
        body: CreateNewPasskeysFactorRequest | CreateNewPasskeysFactorRequestDict,
        *,
        request_options: RequestOptionsOrDict | None = None,
    ) -> V2ServicesPasskeysFactorsResponse:
        """Create a new Passkeys Factor for the Entity

        Args:
            service_sid: The unique SID identifier of the Service.
            body: The request body.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            Created

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (
            await self._with_raw_response.create_new_factor_passkey(service_sid, body, request_options=request_options)
        ).unwrap()

    @property
    def with_raw_response(self) -> AsyncVerifyV2NewFactorWithRawResponse:
        return self._with_raw_response


class VerifyV2NewFactorWithRawResponse(SecuredRawResponse[RawClient, Server, AuthSchemes]):
    def create_new_factor(
        self,
        service_sid: str,
        identity: str,
        friendly_name: str,
        factor_type: NewFactorEnumFactorTypesOrStr,
        *,
        binding_alg: str | None = None,
        binding_public_key: str | None = None,
        config_app_id: str | None = None,
        config_notification_platform: NewFactorEnumNotificationPlatformsOrStr | None = None,
        config_notification_token: str | None = None,
        config_sdk_version: str | None = None,
        binding_secret: str | None = None,
        config_time_step: int | None = None,
        config_skew: int | None = None,
        config_code_length: int | None = None,
        config_alg: NewFactorEnumTotpAlgorithmsOrStr | None = None,
        metadata: Any | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[VerifyV2ServiceEntityNewFactor, RawError]:
        """Create a new Factor for the Entity

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Factor. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            friendly_name: The friendly name of this Factor. This can be any string up to 64 characters, meant for
                humans to distinguish between Factors. For ``factor_type`` ``push``, this could be a device name. For
                ``factor_type`` ``totp``, this value is used as the “account name” in constructing the ``binding.uri``
                property. At the same time, we recommend avoiding providing PII.
            factor_type: The Type of this Factor. Currently ``push`` and ``totp`` are supported.
            binding_alg: The algorithm used when ``factor_type`` is ``push``. Algorithm supported: ``ES256``
            binding_public_key: The Ecdsa public key in PKIX, ASN.1 DER format encoded in Base64. Required when
                ``factor_type`` is ``push``
            config_app_id: The ID that uniquely identifies your app in the Google or Apple store, such as
                ``com.example.myapp``. It can be up to 100 characters long. Required when ``factor_type`` is ``push``.
            config_notification_platform: Value sent with the request.
            config_notification_token: For APN, the device token. For FCM, the registration token. It is used to send
                the push notifications. Must be between 32 and 255 characters long. Required when ``factor_type`` is
                ``push``.
            config_sdk_version: The Verify Push SDK version used to configure the factor Required when ``factor_type``
                is ``push``
            binding_secret: The shared secret for TOTP factors encoded in Base32. This can be provided when creating the
                Factor, otherwise it will be generated. Used when ``factor_type`` is ``totp``
            config_time_step: Defines how often, in seconds, are TOTP codes generated. i.e, a new TOTP code is generated
                every time_step seconds. Must be between 20 and 60 seconds, inclusive. The default value is defined at
                the service level in the property ``totp.time_step``. Defaults to 30 seconds if not configured. Used
                when ``factor_type`` is ``totp``
            config_skew: The number of time-steps, past and future, that are valid for validation of TOTP codes. Must be
                between 0 and 2, inclusive. The default value is defined at the service level in the property
                ``totp.skew``. If not configured defaults to 1. Used when ``factor_type`` is ``totp``
            config_code_length: Number of digits for generated TOTP codes. Must be between 3 and 8, inclusive. The
                default value is defined at the service level in the property ``totp.code_length``. If not configured
                defaults to 6. Used when ``factor_type`` is ``totp``
            config_alg: Value sent with the request.
            metadata: Custom metadata associated with the factor. This is added by the Device/SDK directly to allow for
                the inclusion of device information. It must be a stringified JSON with only strings values eg. ``{"os":
                "Android"}``. Can be up to 1024 characters in length.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="POST",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Factors"),
            path_params=[param[str]("ServiceSid", service_sid), param[str]("Identity", identity)],
            headers=[param[UUID]("Idempotency-Key", uuid4())],
            body=form_body(
                [
                    param[str]("FriendlyName", friendly_name),
                    param[NewFactorEnumFactorTypesOrStr]("FactorType", factor_type),
                    param[str | None]("Binding.Alg", binding_alg),
                    param[str | None]("Binding.PublicKey", binding_public_key),
                    param[str | None]("Config.AppId", config_app_id),
                    param[NewFactorEnumNotificationPlatformsOrStr | None](
                        "Config.NotificationPlatform", config_notification_platform
                    ),
                    param[str | None]("Config.NotificationToken", config_notification_token),
                    param[str | None]("Config.SdkVersion", config_sdk_version),
                    param[str | None]("Binding.Secret", binding_secret),
                    param[int | None]("Config.TimeStep", config_time_step),
                    param[int | None]("Config.Skew", config_skew),
                    param[int | None]("Config.CodeLength", config_code_length),
                    param[NewFactorEnumTotpAlgorithmsOrStr | None]("Config.Alg", config_alg),
                    param[Any | None]("Metadata", metadata),
                ],
            ),
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[VerifyV2ServiceEntityNewFactor],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    def create_new_factor_passkey(
        self,
        service_sid: str,
        body: CreateNewPasskeysFactorRequest | CreateNewPasskeysFactorRequestDict,
        *,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[V2ServicesPasskeysFactorsResponse, RawError]:
        """Create a new Passkeys Factor for the Entity

        Args:
            service_sid: The unique SID identifier of the Service.
            body: The request body.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="POST",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Passkeys/Factors"),
            path_params=[param[str]("ServiceSid", service_sid)],
            headers=[param[UUID]("Idempotency-Key", uuid4())],
            body=json_body[CreateNewPasskeysFactorRequest | CreateNewPasskeysFactorRequestDict](body),
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[V2ServicesPasskeysFactorsResponse],
            error_mapper=raw_error_response,
            request_options=request_options,
        )


class AsyncVerifyV2NewFactorWithRawResponse(SecuredRawResponse[AsyncRawClient, Server, AsyncAuthSchemes]):
    async def create_new_factor(
        self,
        service_sid: str,
        identity: str,
        friendly_name: str,
        factor_type: NewFactorEnumFactorTypesOrStr,
        *,
        binding_alg: str | None = None,
        binding_public_key: str | None = None,
        config_app_id: str | None = None,
        config_notification_platform: NewFactorEnumNotificationPlatformsOrStr | None = None,
        config_notification_token: str | None = None,
        config_sdk_version: str | None = None,
        binding_secret: str | None = None,
        config_time_step: int | None = None,
        config_skew: int | None = None,
        config_code_length: int | None = None,
        config_alg: NewFactorEnumTotpAlgorithmsOrStr | None = None,
        metadata: Any | None = None,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[VerifyV2ServiceEntityNewFactor, RawError]:
        """Create a new Factor for the Entity

        Args:
            service_sid: The unique SID identifier of the Service.
            identity: Customer unique identity for the Entity owner of the Factor. This identifier should be immutable,
                not PII, length between 8 and 64 characters, and generated by your external system, such as your user's
                UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
            friendly_name: The friendly name of this Factor. This can be any string up to 64 characters, meant for
                humans to distinguish between Factors. For ``factor_type`` ``push``, this could be a device name. For
                ``factor_type`` ``totp``, this value is used as the “account name” in constructing the ``binding.uri``
                property. At the same time, we recommend avoiding providing PII.
            factor_type: The Type of this Factor. Currently ``push`` and ``totp`` are supported.
            binding_alg: The algorithm used when ``factor_type`` is ``push``. Algorithm supported: ``ES256``
            binding_public_key: The Ecdsa public key in PKIX, ASN.1 DER format encoded in Base64. Required when
                ``factor_type`` is ``push``
            config_app_id: The ID that uniquely identifies your app in the Google or Apple store, such as
                ``com.example.myapp``. It can be up to 100 characters long. Required when ``factor_type`` is ``push``.
            config_notification_platform: Value sent with the request.
            config_notification_token: For APN, the device token. For FCM, the registration token. It is used to send
                the push notifications. Must be between 32 and 255 characters long. Required when ``factor_type`` is
                ``push``.
            config_sdk_version: The Verify Push SDK version used to configure the factor Required when ``factor_type``
                is ``push``
            binding_secret: The shared secret for TOTP factors encoded in Base32. This can be provided when creating the
                Factor, otherwise it will be generated. Used when ``factor_type`` is ``totp``
            config_time_step: Defines how often, in seconds, are TOTP codes generated. i.e, a new TOTP code is generated
                every time_step seconds. Must be between 20 and 60 seconds, inclusive. The default value is defined at
                the service level in the property ``totp.time_step``. Defaults to 30 seconds if not configured. Used
                when ``factor_type`` is ``totp``
            config_skew: The number of time-steps, past and future, that are valid for validation of TOTP codes. Must be
                between 0 and 2, inclusive. The default value is defined at the service level in the property
                ``totp.skew``. If not configured defaults to 1. Used when ``factor_type`` is ``totp``
            config_code_length: Number of digits for generated TOTP codes. Must be between 3 and 8, inclusive. The
                default value is defined at the service level in the property ``totp.code_length``. If not configured
                defaults to 6. Used when ``factor_type`` is ``totp``
            config_alg: Value sent with the request.
            metadata: Custom metadata associated with the factor. This is added by the Device/SDK directly to allow for
                the inclusion of device information. It must be a stringified JSON with only strings values eg. ``{"os":
                "Android"}``. Can be up to 1024 characters in length.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="POST",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Factors"),
            path_params=[param[str]("ServiceSid", service_sid), param[str]("Identity", identity)],
            headers=[param[UUID]("Idempotency-Key", uuid4())],
            body=form_body(
                [
                    param[str]("FriendlyName", friendly_name),
                    param[NewFactorEnumFactorTypesOrStr]("FactorType", factor_type),
                    param[str | None]("Binding.Alg", binding_alg),
                    param[str | None]("Binding.PublicKey", binding_public_key),
                    param[str | None]("Config.AppId", config_app_id),
                    param[NewFactorEnumNotificationPlatformsOrStr | None](
                        "Config.NotificationPlatform", config_notification_platform
                    ),
                    param[str | None]("Config.NotificationToken", config_notification_token),
                    param[str | None]("Config.SdkVersion", config_sdk_version),
                    param[str | None]("Binding.Secret", binding_secret),
                    param[int | None]("Config.TimeStep", config_time_step),
                    param[int | None]("Config.Skew", config_skew),
                    param[int | None]("Config.CodeLength", config_code_length),
                    param[NewFactorEnumTotpAlgorithmsOrStr | None]("Config.Alg", config_alg),
                    param[Any | None]("Metadata", metadata),
                ],
            ),
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[VerifyV2ServiceEntityNewFactor],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    async def create_new_factor_passkey(
        self,
        service_sid: str,
        body: CreateNewPasskeysFactorRequest | CreateNewPasskeysFactorRequestDict,
        *,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[V2ServicesPasskeysFactorsResponse, RawError]:
        """Create a new Passkeys Factor for the Entity

        Args:
            service_sid: The unique SID identifier of the Service.
            body: The request body.
            request_options: Per-call overrides for this one request, such as a timeout or extra headers.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="POST",
            url_template=self._server.default3("/v2/Services/{ServiceSid}/Passkeys/Factors"),
            path_params=[param[str]("ServiceSid", service_sid)],
            headers=[param[UUID]("Idempotency-Key", uuid4())],
            body=json_body[CreateNewPasskeysFactorRequest | CreateNewPasskeysFactorRequestDict](body),
            auth_scheme=self._auth.account_sid_auth_token,
            decoder=json_decoder[V2ServicesPasskeysFactorsResponse],
            error_mapper=raw_error_response,
            request_options=request_options,
        )
