from enum import Enum
from typing import Annotated, TypeAlias

from ...core import open_enum_validator


class RequestMethod(str, Enum):
    """The HTTP method used to generate the notification. If the notification was generated during a phone call, this is
    the HTTP Method used to request the resource on your server. If the notification was generated by your use of our
    REST API, this is the HTTP method used to call the resource on our servers."""

    GET = "GET"
    POST = "POST"

    __str__ = str.__str__


RequestMethodOrStr: TypeAlias = Annotated[RequestMethod | str, open_enum_validator(RequestMethod)]
