from enum import Enum
from typing import Annotated, TypeAlias

from ...core import open_enum_validator


class DocumentType(str, Enum):
    """The type of document."""

    SC_LETTER_OF_AUTHORIZATION = "SC_LETTER_OF_AUTHORIZATION"
    CALL_TO_ACTION_OR_OPT_IN_MOCKUP = "CALL_TO_ACTION_OR_OPT_IN_MOCKUP"
    SMS_CAMPAIGN_TERMS_OF_SERVICE = "SMS_CAMPAIGN_TERMS_OF_SERVICE"
    SMS_PRIVACY_POLICY = "SMS_PRIVACY_POLICY"
    MIGRATION_REQUEST_LETTER = "MIGRATION_REQUEST_LETTER"
    SHORT_CODE_LEASE_RECEIPT = "SHORT_CODE_LEASE_RECEIPT"
    ADDITIONAL_SUPPORTING_DOCUMENTS_1 = "ADDITIONAL_SUPPORTING_DOCUMENTS_1"
    ADDITIONAL_SUPPORTING_DOCUMENTS_2 = "ADDITIONAL_SUPPORTING_DOCUMENTS_2"
    ADDITIONAL_SUPPORTING_DOCUMENTS_3 = "ADDITIONAL_SUPPORTING_DOCUMENTS_3"
    ADDITIONAL_SUPPORTING_DOCUMENTS_4 = "ADDITIONAL_SUPPORTING_DOCUMENTS_4"
    ADDITIONAL_SUPPORTING_DOCUMENTS_5 = "ADDITIONAL_SUPPORTING_DOCUMENTS_5"
    ADDITIONAL_SUPPORTING_DOCUMENTS_6 = "ADDITIONAL_SUPPORTING_DOCUMENTS_6"
    ADDITIONAL_SUPPORTING_DOCUMENTS_7 = "ADDITIONAL_SUPPORTING_DOCUMENTS_7"
    ADDITIONAL_SUPPORTING_DOCUMENTS_8 = "ADDITIONAL_SUPPORTING_DOCUMENTS_8"
    ADDITIONAL_SUPPORTING_DOCUMENTS_9 = "ADDITIONAL_SUPPORTING_DOCUMENTS_9"
    ADDITIONAL_SUPPORTING_DOCUMENTS_10 = "ADDITIONAL_SUPPORTING_DOCUMENTS_10"

    __str__ = str.__str__


DocumentTypeOrStr: TypeAlias = Annotated[DocumentType | str, open_enum_validator(DocumentType)]
