from __future__ import annotations

from typing import Any

from pydantic import AnyUrl
from typing_extensions import NotRequired, TypedDict

from ..core import UNSET, Optional, OptionalNullable, RFC3339DateTime, SdkBaseModel
from .enums.new_factor_enum_factor_statuses import NewFactorEnumFactorStatusesOrStr
from .enums.new_factor_enum_factor_types import NewFactorEnumFactorTypesOrStr


class VerifyV2ServiceEntityNewFactor(SdkBaseModel):
    sid: OptionalNullable[str] = UNSET
    """A 34 character string that uniquely identifies this Factor."""

    account_sid: OptionalNullable[str] = UNSET
    """The unique SID identifier of the Account."""

    service_sid: OptionalNullable[str] = UNSET
    """The unique SID identifier of the Service."""

    entity_sid: OptionalNullable[str] = UNSET
    """The unique SID identifier of the Entity."""

    identity: OptionalNullable[str] = UNSET
    """Customer unique identity for the Entity owner of the Factor. This identifier should be immutable, not PII, length
    between 8 and 64 characters, and generated by your external system, such as your user's UUID, GUID, or SID. It can
    only contain dash (-) separated alphanumeric characters."""

    binding: OptionalNullable[Any] = UNSET
    """Contains the ``factor_type`` specific secret and metadata. For push, this is ``binding.public_key`` and
    ``binding.alg``. For totp, this is ``binding.secret`` and ``binding.uri``. The ``binding.uri`` property is generated
    following the `google authenticator key URI format
    <https://github.com/google/google-authenticator/wiki/Key-Uri-Format>`__, and ``Factor.friendly_name`` is used for
    the “accountname” value and ``Service.friendly_name`` or ``Service.totp.issuer`` is used for the ``issuer`` value.


    The Binding property is ONLY returned upon Factor creation."""

    options: OptionalNullable[Any] = UNSET
    date_created: OptionalNullable[RFC3339DateTime] = UNSET
    """The date that this Factor was created, given in `ISO 8601 <https://en.wikipedia.org/wiki/ISO_8601>`__ format."""

    date_updated: OptionalNullable[RFC3339DateTime] = UNSET
    """The date that this Factor was updated, given in `ISO 8601 <https://en.wikipedia.org/wiki/ISO_8601>`__ format."""

    friendly_name: OptionalNullable[str] = UNSET
    """The friendly name of this Factor. This can be any string up to 64 characters, meant for humans to distinguish
    between Factors. For ``factor_type`` ``push``, this could be a device name. For ``factor_type`` ``totp``, this value
    is used as the “account name” in constructing the ``binding.uri`` property. At the same time, we recommend avoiding
    providing PII."""

    status: Optional[NewFactorEnumFactorStatusesOrStr] = UNSET
    """The Status of this Factor. One of ``unverified`` or ``verified``."""

    factor_type: Optional[NewFactorEnumFactorTypesOrStr] = UNSET
    """The Type of this Factor. Currently ``push`` and ``totp`` are supported."""

    config: OptionalNullable[Any] = UNSET
    """An object that contains configurations specific to a ``factor_type``."""

    metadata: OptionalNullable[Any] = UNSET
    """Custom metadata associated with the factor. This is added by the Device/SDK directly to allow for the inclusion
    of device information. It must be a stringified JSON with only strings values eg. ``{"os": "Android"}``. Can be up
    to 1024 characters in length."""

    url: OptionalNullable[AnyUrl] = UNSET
    """The URL of this resource."""


class VerifyV2ServiceEntityNewFactorDict(TypedDict):
    sid: NotRequired[str | None]
    account_sid: NotRequired[str | None]
    service_sid: NotRequired[str | None]
    entity_sid: NotRequired[str | None]
    identity: NotRequired[str | None]
    binding: NotRequired[Any | None]
    options: NotRequired[Any | None]
    date_created: NotRequired[RFC3339DateTime | None]
    date_updated: NotRequired[RFC3339DateTime | None]
    friendly_name: NotRequired[str | None]
    status: NotRequired[NewFactorEnumFactorStatusesOrStr]
    factor_type: NotRequired[NewFactorEnumFactorTypesOrStr]
    config: NotRequired[Any | None]
    metadata: NotRequired[Any | None]
    url: NotRequired[AnyUrl | None]
