from __future__ import annotations

from typing import Any

from pydantic import AnyUrl
from typing_extensions import NotRequired, TypedDict

from ..core import UNSET, Optional, OptionalNullable, RFC3339DateTime, SdkBaseModel
from .enums.challenge_enum_challenge_reasons import ChallengeEnumChallengeReasonsOrStr
from .enums.challenge_enum_challenge_statuses import ChallengeEnumChallengeStatusesOrStr
from .enums.challenge_enum_factor_types import ChallengeEnumFactorTypesOrStr


class VerifyV2ServiceEntityChallenge(SdkBaseModel):
    sid: OptionalNullable[str] = UNSET
    """A 34 character string that uniquely identifies this Challenge."""

    account_sid: OptionalNullable[str] = UNSET
    """The unique SID identifier of the Account."""

    service_sid: OptionalNullable[str] = UNSET
    """The unique SID identifier of the Service."""

    entity_sid: OptionalNullable[str] = UNSET
    """The unique SID identifier of the Entity."""

    identity: OptionalNullable[str] = UNSET
    """Customer unique identity for the Entity owner of the Challenge. This identifier should be immutable, not PII,
    length between 8 and 64 characters, and generated by your external system, such as your user's UUID, GUID, or SID.
    It can only contain dash (-) separated alphanumeric characters."""

    factor_sid: OptionalNullable[str] = UNSET
    """The unique SID identifier of the Factor."""

    date_created: OptionalNullable[RFC3339DateTime] = UNSET
    """The date that this Challenge was created, given in `ISO 8601 <https://en.wikipedia.org/wiki/ISO_8601>`__
    format."""

    date_updated: OptionalNullable[RFC3339DateTime] = UNSET
    """The date that this Challenge was updated, given in `ISO 8601 <https://en.wikipedia.org/wiki/ISO_8601>`__
    format."""

    date_responded: OptionalNullable[RFC3339DateTime] = UNSET
    """The date that this Challenge was responded, given in `ISO 8601 <https://en.wikipedia.org/wiki/ISO_8601>`__
    format."""

    expiration_date: OptionalNullable[RFC3339DateTime] = UNSET
    """The date-time when this Challenge expires, given in `ISO 8601 <https://en.wikipedia.org/wiki/ISO_8601>`__ format.
    The default value is five (5) minutes after Challenge creation. The max value is sixty (60) minutes after
    creation."""

    status: Optional[ChallengeEnumChallengeStatusesOrStr] = UNSET
    """The Status of this Challenge. One of ``pending``, ``expired``, ``approved`` or ``denied``."""

    responded_reason: Optional[ChallengeEnumChallengeReasonsOrStr] = UNSET
    """Reason for the Challenge to be in certain ``status``. One of ``none``, ``not_needed`` or ``not_requested``."""

    details: OptionalNullable[Any] = UNSET
    """Details provided to give context about the Challenge. Intended to be shown to the end user."""

    hidden_details: OptionalNullable[Any] = UNSET
    """Details provided to give context about the Challenge. Intended to be hidden from the end user. It must be a
    stringified JSON with only strings values eg. ``{"ip": "172.168.1.234"}``"""

    metadata: OptionalNullable[Any] = UNSET
    """Custom metadata associated with the challenge. This is added by the Device/SDK directly to allow for the
    inclusion of device information. It must be a stringified JSON with only strings values eg. ``{"os": "Android"}``.
    Can be up to 1024 characters in length."""

    factor_type: Optional[ChallengeEnumFactorTypesOrStr] = UNSET
    """The Factor Type of this Challenge. Currently ``push`` and ``totp`` are supported."""

    url: OptionalNullable[AnyUrl] = UNSET
    """The URL of this resource."""

    links: OptionalNullable[Any] = UNSET
    """Contains a dictionary of URL links to nested resources of this Challenge."""


class VerifyV2ServiceEntityChallengeDict(TypedDict):
    sid: NotRequired[str | None]
    account_sid: NotRequired[str | None]
    service_sid: NotRequired[str | None]
    entity_sid: NotRequired[str | None]
    identity: NotRequired[str | None]
    factor_sid: NotRequired[str | None]
    date_created: NotRequired[RFC3339DateTime | None]
    date_updated: NotRequired[RFC3339DateTime | None]
    date_responded: NotRequired[RFC3339DateTime | None]
    expiration_date: NotRequired[RFC3339DateTime | None]
    status: NotRequired[ChallengeEnumChallengeStatusesOrStr]
    responded_reason: NotRequired[ChallengeEnumChallengeReasonsOrStr]
    details: NotRequired[Any | None]
    hidden_details: NotRequired[Any | None]
    metadata: NotRequired[Any | None]
    factor_type: NotRequired[ChallengeEnumFactorTypesOrStr]
    url: NotRequired[AnyUrl | None]
    links: NotRequired[Any | None]
