from __future__ import annotations

from typing_extensions import NotRequired, TypedDict

from ..core import UNSET, Optional, OptionalNullable, RFC3339DateTime, SdkBaseModel


class VerifyV2ServiceEntityChallengeNotification(SdkBaseModel):
    sid: OptionalNullable[str] = UNSET
    """A 34 character string that uniquely identifies this Notification."""

    account_sid: OptionalNullable[str] = UNSET
    """The unique SID identifier of the Account."""

    service_sid: OptionalNullable[str] = UNSET
    """The unique SID identifier of the Service."""

    entity_sid: OptionalNullable[str] = UNSET
    """The unique SID identifier of the Entity."""

    identity: OptionalNullable[str] = UNSET
    """Customer unique identity for the Entity owner of the Challenge. This identifier should be immutable, not PII,
    length between 8 and 64 characters, and generated by your external system, such as your user's UUID, GUID, or SID.
    It can only contain dash (-) separated alphanumeric characters."""

    challenge_sid: OptionalNullable[str] = UNSET
    """The unique SID identifier of the Challenge."""

    priority: OptionalNullable[str] = UNSET
    """The priority of the notification. For ``push`` Challenges it's always ``high`` which sends the notification
    immediately, and can wake up a sleeping device."""

    ttl: Optional[int] = UNSET
    """How long, in seconds, the notification is valid. Max: 5 minutes"""

    date_created: OptionalNullable[RFC3339DateTime] = UNSET
    """The date that this Notification was created, given in `ISO 8601 <https://en.wikipedia.org/wiki/ISO_8601>`__
    format."""


class VerifyV2ServiceEntityChallengeNotificationDict(TypedDict):
    sid: NotRequired[str | None]
    account_sid: NotRequired[str | None]
    service_sid: NotRequired[str | None]
    entity_sid: NotRequired[str | None]
    identity: NotRequired[str | None]
    challenge_sid: NotRequired[str | None]
    priority: NotRequired[str | None]
    ttl: NotRequired[int]
    date_created: NotRequired[RFC3339DateTime | None]
